# 1. Create a null vector of size 10

In [1]:
import numpy as np
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 2. How to find the memory size of an array

In [2]:
arr1.nbytes

80

# 3. Create a null vector of size 10 but the fifth value which is 1 

In [3]:
arr1 = np.zeros(10)
arr1
arr1[4] = 1 
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 4. Create a vector with values ranging from 15 to 45 

In [4]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

# 5. Reverse a vector (The first element becomes last)


In [5]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [6]:
arr2 = list(reversed(arr1))
arr2

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

# 6. Write a Numpy program to add , subtract , multiply , divide arguments element - wise 

In [7]:
arr1 = np.random.randint(10,20,size=(2,2))
print("\narray 1 : ", arr1)
arr2 = np.random.randint(50,70,size=(2,2))
print("\narray 2 : ", arr2)


array 1 :  [[10 18]
 [17 11]]

array 2 :  [[65 51]
 [56 64]]


In [8]:
add = arr1 + arr2
add

array([[75, 69],
       [73, 75]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[-55, -33],
       [-39, -53]])

# 7. Write a Numpy program to round elements of the array to the nearest integer

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

# 8. Numpy program to get the floor and ceiling values of the elements of the array 

In [13]:
import math 
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

# 9. Write a Numpy program to calculate mean across dimensions in a 2D Numpy array

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_row = np.mean(arr1 , axis=1)
print("Mean across row >>" , mean_row)
mean_col = np.mean(arr1 , axis=0)
print("Mean across col >>" , mean_col)

Mean across row >> [2. 5. 8.]
Mean across col >> [4. 5. 6.]


# 10. Write a Numpy program to convert angles from degrees to radians for all elements in a given array

In [16]:
list1 = [0,30,45,60,90]
degTorad = np.deg2rad(list1)
degTorad

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

# 11. What is the use of all and any functions in Numpy?

1. "numpy.all()"
* Checks if all elements are True.
* Example : np.all([True,True,False]) returns False
2. "numpy.any()"
* Checks if any elements are True.
* Example : np.any([True,True,False]) returns True

# 12. Create a 3*3 matrix with values ranging from 0 to 8 

In [17]:
arr1 = np.arange(9).reshape(3,3)
print("Matrix is :\n", arr1)

Matrix is :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


# 13. How to reverse the columns of a 2D array?

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix is :\n", arr1)
arr1[:: , ::-1]

Matrix is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

# 14. How to reverse the rows of a 2D array?

In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix is :\n", arr1)
arr1[::-1]

Matrix is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

# 15. Find indices of non zero elements from [1,2,0,0,4,0]

In [20]:
result = np.nonzero([1,2,0,0,4,0])
print(result)

(array([0, 1, 4], dtype=int64),)


# 16. Write a numpy program to compute the determinant of an array

In [21]:
arr1 = np.array([[1,2],[3,4]])
print("Matrix is :\n", arr1)
result = np.linalg.det(arr1)
print("Determinant of the said array:")
print(result)

Matrix is :
 [[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


# 17. Write a numpy program to compute the inverse of given matrix

In [22]:
arr1 = np.array([[2,3],[3,9]])
print("Matrix is :\n", arr1)
np.linalg.inv(arr1)

Matrix is :
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

# 18. Create a random vector of size 30 and find the mean value 

In [24]:
arr1 = np.random.randint(10,30,size=(30))
print("Matrix is :\n", arr1)
mean = np.mean(arr1)
print("Mean of array1 is :", mean)

Matrix is :
 [26 29 29 22 25 22 11 17 18 13 27 11 10 15 20 25 27 18 13 18 22 13 23 17
 14 23 16 19 23 24]
Mean of array1 is : 19.666666666666668


# 19. How to extract all numbers between a given range from a Numpy array?

In [25]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
arr2 = np.where(arr1 > 5) # It will give you index number 
print("Array :",arr2)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Array : (array([5, 6, 7, 8, 9], dtype=int64),)


# 20. Create a 3*3*3 array with random values

In [27]:
arr1 = np.random.random((3,3,3))
print("Array :\n",arr1)

Array :
 [[[0.80719587 0.06537145 0.2548252 ]
  [0.02806048 0.16946448 0.36137043]
  [0.87340606 0.80446588 0.95500703]]

 [[0.00536116 0.3901278  0.26947938]
  [0.32260611 0.62589136 0.17299483]
  [0.69649678 0.99028186 0.41986193]]

 [[0.88584483 0.66512424 0.80759712]
  [0.45066764 0.36821323 0.96398879]
  [0.30445575 0.62997417 0.19783575]]]


# 21. Create a 10*10 array with random values and find the maximun and minimum values

In [28]:
arr1 = np.random.rand(10,10)
print("Array:",arr1)
print("Maximum value:\n" , np.max(arr1))
print("Minimum value:\n" , np.min(arr1))

Array: [[0.61131455 0.54125431 0.70445709 0.84926964 0.77369963 0.34015472
  0.37765998 0.63272326 0.10603626 0.14082737]
 [0.96296654 0.09162853 0.51746206 0.51152899 0.50245482 0.14421403
  0.00506938 0.04720945 0.99180124 0.48131757]
 [0.82680833 0.15305898 0.46396965 0.5954722  0.47718491 0.38690148
  0.410473   0.74664996 0.32582062 0.48167577]
 [0.84621454 0.52513016 0.0036642  0.15963131 0.29172284 0.64345261
  0.72086893 0.28722812 0.88889282 0.36338163]
 [0.93491229 0.75620313 0.37736104 0.20519599 0.64748947 0.05084314
  0.44440224 0.25225338 0.08560304 0.40489392]
 [0.48169258 0.48664976 0.48015238 0.29881674 0.77201207 0.64030262
  0.76386585 0.95029904 0.7423655  0.95416519]
 [0.37665535 0.27511838 0.11163848 0.66139506 0.3412032  0.14150719
  0.4276949  0.94313993 0.07524826 0.54192293]
 [0.86470692 0.0504035  0.79310158 0.17818552 0.64060983 0.29498085
  0.95742494 0.18635045 0.31120012 0.13293877]
 [0.51771943 0.37695244 0.25011595 0.9990723  0.65200866 0.7687438
  0.37

# 22. Create a 2D array with 1 on the border and 0 inside

In [31]:
arr1 = np.ones((10 , 10))
arr1[1:-1 ,1:-1] = 0
print(arr1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 23. Create a 5*5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
arr1 = np.zeros((5,5) , dtype=int)
np.fill_diagonal(arr1[1:] , [1,2,3,4])
print(arr1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 24. Create a 3*3 identity matrix

In [33]:
arr1 = np.eye(3,3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 25. Create a 8*8 matrix and fill it with a checkboard pattern

In [34]:
matrix_size = 8
checkerboard = [[0] * matrix_size for i in range(matrix_size)]

for i in range(matrix_size):
    for j in range(matrix_size):
        checkerboard[i][j] = (i + j) % 2

for row in checkerboard:
    print(row)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


# 26. Multiply a 5 * 3 matrix by a 3 * 2 matrix (real matrix product)

In [35]:
arr1 = np.random.randint(1,9, size=(5,3))
arr2 = np.random.randint(1,9, size=(3,2))
arr = np.dot(arr1, arr2)
print("Array 1 :\n",arr1)
print("Array 2 :\n",arr2)
print("Multiplication array :\n",arr)

Array 1 :
 [[5 7 6]
 [5 5 3]
 [1 8 6]
 [6 1 3]
 [5 1 1]]
Array 2 :
 [[3 3]
 [2 2]
 [3 8]]
Multiplication array :
 [[47 77]
 [34 49]
 [37 67]
 [29 44]
 [20 25]]


# 27. Given a 1D array , negate all elements which are between 3 and 8 inplace 

In [36]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
arr1[(arr1>=3) & (arr1<=8)] *=-1
print("Original array:\n" , arr1)
print("New array:\n" , arr2)    

Original array:
 [ 1  2 -3 -4 -5 -6 -7 -8 44  9 33 -6 -5 10]
New array:
 [[3 3]
 [2 2]
 [3 8]]


In [37]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
arr2 = np.where((arr1>=3) & (arr1<=8) , -1*arr1 , arr1)
print("Original array:\n" , arr1)
print("New array:\n" , arr2)

Original array:
 [ 1  2  3  4  5  6  7  8 44  9 33  6  5 10]
New array:
 [ 1  2 -3 -4 -5 -6 -7 -8 44  9 33 -6 -5 10]


# 28. How to round away from zero a float array?

In [38]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Original array:\n" , arr1)
print("New array:\n" , np.around(arr1 , 1))

Original array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]
New array:
 [[1.2 2.7]
 [3.5 5.2]]


In [41]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
rounded_up = np.ceil(arr1)
rounded_down = np.floor(arr1)
print("Original array :" , arr1)
print("Rounded up :\n" , rounded_up)
print("Rounded down :\n" , rounded_down)

Original array : [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]
Rounded up :
 [[2. 3.]
 [4. 6.]]
Rounded down :
 [[1. 2.]
 [3. 5.]]


# 29. How to find the common values between the two arrays?

In [40]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
common = np.intersect1d(arr1, arr2)
print("Common values :",common)

Common values : [4 5 6]


# 30. Create a vector of size 10 with values ranging from 0 to 1 both excluded 

In [42]:
arr1 = np.linspace(0,1,10)[1:-1]
print("Vector is:\n",arr1)

Vector is:
 [0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


# 31. Create a random vector of size 10 and sort it

In [43]:
arr1 = np.random.randint(1,10,size=10)
print("Array : ",arr1)
arr2 = np.sort(arr1)
print("Sorted array : ",arr2)

Array :  [9 4 7 9 7 9 8 3 9 8]
Sorted array :  [3 4 7 7 8 8 9 9 9 9]


# 32. Create a 5*5 matrix with row values ranging from 0 to 4

In [44]:
arr1 = np.zeros((5,5))
print("Original array:\n",arr1)
arr2 = arr1 + np.arange(5)
print("New array:\n",arr2)

Original array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
New array:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 33. Consider two random arrays A and B , check if they are equal

In [45]:
A = np.random.randint(0,5,size=5)
B = np.random.randint(0,5,size=5)
if np.equal==True:
    print("Both arrays are equal")
else:
    print("Both arrays are different")

Both arrays are different


In [46]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
print("Both arrays are equal or not:\n" , np.allclose(arr1, arr2))


Both arrays are equal or not:
 False


# 34. Create a random vector of size 10 and replace the maximum value by 0

In [48]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
arr1[arr1.argmax()] = 0
print("Maximum value replaced by 0.:\n", arr1)

Array: [4 6 8 8 5 9 9 1 5 3]
Maximum value replaced by 0.:
 [4 6 8 8 5 0 9 1 5 3]


# 35. How to find out the multiple indices of an item?

In [49]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i , end=" ")
    

1 2 3 4 5 6 7 8 9 

# 36. What is the equivalent of enumerate for Numpy arrays

In [50]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f" {index} index has {value} values")

 (0, 0) index has 1 values
 (0, 1) index has 2 values
 (0, 2) index has 3 values
 (1, 0) index has 4 values
 (1, 1) index has 5 values
 (1, 2) index has 6 values
 (2, 0) index has 7 values
 (2, 1) index has 8 values
 (2, 2) index has 9 values


# 37. How to sort an array by the nth column?

In [54]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array is :\n" , arr1)
sorted_array = (arr1[arr1[:,2].argsort()])
print("Sorted array:\n" , sorted_array)

Array is :
 [[5 6 7]
 [6 1 7]
 [3 7 6]]
Sorted array:
 [[3 7 6]
 [5 6 7]
 [6 1 7]]


# 38. How to swap two rows of an array

In [55]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array is :\n" , arr1)
arr1[[0,2]] = arr1[[2,0]]
print("Swapped array is :\n" , arr1)

Array is :
 [[4 3 1]
 [5 8 9]
 [3 4 5]]
Swapped array is :
 [[3 4 5]
 [5 8 9]
 [4 3 1]]


# 39. How to compute the mean of the Numpy array?

In [56]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean of the Numpy array is :" , np.mean(arr1))

Mean of the Numpy array is : 5.5


# 40. How to compute the median of the Numpy array?

In [57]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Median of the Numpy array is :" , np.median(arr1))


Median of the Numpy array is : 5.5


# 41. How to compute the standard deviation of the Numpy array?

In [58]:
arr1 = np.random.randint(1,10,size =10)
print(arr1)
print()
print("Standard deviation of the Numpy array :" , np.std(arr1))


[6 7 8 8 7 2 8 5 1 8]

Standard deviation of the Numpy array : 2.449489742783178


# 42. How to compute the mode of the Numpy array?

In [62]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
mode1= mode(arr1)

print("Mode of the Numpy array: ", mode1)

Mode of the Numpy array:  ModeResult(mode=1, count=1)


# 43. How to print only 3 decimal places in a python NumPy array?

In [63]:
result = np.around(5.24435 , 3)
result

5.244

# 44. Write a Numpy program to compute the inverse of the given matrix

In [65]:
arr1 = np.array([[2,3],[3,4]])
print("Original matrix: ", arr1)
print("Inverse of the original matrix:\n",np.linalg.inv(arr1))


Original matrix:  [[2 3]
 [3 4]]
Inverse of the original matrix:
 [[-4.  3.]
 [ 3. -2.]]


# 45. Write a Numpy program to compute the covariance matrix of two given arrays

In [67]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print("Covariance of the two arrays:\n",np.cov(x,y))


Covariance of the two arrays:
 [[1. 1.]
 [1. 1.]]


# 46. How to find the most frequent value in a NumPy array

In [68]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
mode1 = mode(arr1)[0]
print("Mode of the array is : ", mode1)


Mode of the array is :  6


# 47. How to convert 1D array to 3D array?

In [70]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print("Dimension of the array is:",arr1.ndim)
arr1.shape
arr2 = np.reshape(arr1 , (2,5,1))
print(arr2)
print("Dimension of the array is:",arr2.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension of the array is: 1
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
Dimension of the array is: 3


# 48. How to convert 4D array to 2D array?

In [71]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print(arr1)
print("Dimension of arr1 is:",arr1.ndim)
arr2 = np.reshape(arr1 , (6,4))
print(arr2)
print("Dimension of arr2 is:",arr2.ndim)

[[[[18 12  3  6]
   [15  5  4  5]
   [ 8 11  1  2]]

  [[13  4  3 19]
   [ 1 10  8 15]
   [ 1 18  4 17]]]]
Dimension of arr1 is: 4
[[18 12  3  6]
 [15  5  4  5]
 [ 8 11  1  2]
 [13  4  3 19]
 [ 1 10  8 15]
 [ 1 18  4 17]]
Dimension of arr2 is: 2


# 49. Create a numpy array filled with all zeros

In [72]:
arr1 = np.zeros(10 , dtype=int)
print(arr1)

[0 0 0 0 0 0 0 0 0 0]


# 50. Find the number of rows and columns of a given matrix using Numpy

In [74]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Matrix:\n",arr1)
print("Shape of the array:",arr1.shape)

Matrix:
 [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]
Shape of the array: (3, 4)
