# Decision Tree Multiclass Classification 

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,roc_auc_score,roc_curve

import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
df.drop("Id",axis=1,inplace=True)

In [4]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
x=df.drop("Species",axis=1)
y=df["Species"]

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=12,stratify=y)


Model Training 

In [7]:
dt_clf=DecisionTreeClassifier()
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier()

Model Evaluation on Testing data

In [8]:
y_pred_test=dt_clf.predict(x_test)
cnf_matrix = confusion_matrix(y_test,y_pred_test)
print("Confusion Matrix:\n",cnf_matrix)
print("*"*80)
accuracy = accuracy_score(y_test,y_pred_test)
print("Accuracy: ", accuracy)
print("*"*80)
clf_report=classification_report(y_test,y_pred_test)
print("Clf Report:\n",clf_report)

Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
********************************************************************************
Accuracy:  1.0
********************************************************************************
Clf Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        10
 Iris-virginica       1.00      1.00      1.00        10

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



Model Evaluation on training data

In [9]:
y_pred_train = dt_clf.predict(x_train)
cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("Confusion matrix:\n",cnf_matrix)
print("*"*80)
accuracy=accuracy_score(y_train,y_pred_train)
print("Accuracy:",accuracy)
print("*"*80)
clf_report=classification_report(y_train,y_pred_train)
print("Clf report:\n",clf_report)

Confusion matrix:
 [[40  0  0]
 [ 0 40  0]
 [ 0  0 40]]
********************************************************************************
Accuracy: 1.0
********************************************************************************
Clf report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        40
Iris-versicolor       1.00      1.00      1.00        40
 Iris-virginica       1.00      1.00      1.00        40

       accuracy                           1.00       120
      macro avg       1.00      1.00      1.00       120
   weighted avg       1.00      1.00      1.00       120



In [10]:
plt.figure(figsize=(200,100))
plot_tree(dt_clf,feature_names=x.columns.to_list(),filled=True,class_names=['setosa','versicolor','virginica'])
plt.savefig("DT_Multiclass_clf_withoutHYP.png")