* Large dataset === No of rows >> No of columns 
* High Dimensional dataset === No of columns >> No of rows 

1. Naive Bayes 
2. Suport vector machine 

1. Naive Bayes 
* Bayes theroem 
* Sentiment analysis
* Spam information 

* Probablity  >> S ={H,T}
* Cards >> 52 >> 13 + 13 + 13 +13 +13

* Bag1 = Red4,Green3      Bag2 = Red3,Green2
* Prob(Red) = [prob(Bag1) * prob(Red/Bag1)] + [prob(bag2) * prob(Red/Bag2)]

> Bayes theroem
* Prob(A/B) = Prob(A) * Prob(B/A) / Prob(B)
* Prob of A given B = Prob A when B event occured 
* P(A U B) = P(A) + P(B) - P(A intersection B)
* P(A/B) = P(A intersectio B) / Prob(B)
* P(B/A) = P(B intersectio A) / Prob(A)

> P(A/B) = P(A) * P(B/A) / P(B)    >> Bayes Theroem 
* X > Independent varaiable 
* Y > Dependent varaiable 
* Prob(Y/X) = Prob(Y) * Prob(X/Y) / Prob(X) 
* Multiple independent variables 
* Prob(Y/{X1,X2}) = Prob(X1/Y) * prob(X2/Y) * Prob(Y) / Prob(X1) * prob(X2)
* Posterier probablity = Likelihood prob * prior probablity / Marginal probablity 
* Posterier probablity = likelihood prob * prior probablity / Marginal likelihood

> probablity (Y=1|{X1,X2,X3}) = prob(X1/Y) * Prob(X2/Y) * Prob(X3/Y) * Prob(Yes) / Prob(X1) * prob(X2) * prob(X3)

> Text to numeric 
1. BOW (Bag of Words)
2. TF-IDF

1. Bag of words 
* Used to convert text to numeric.

In [5]:
text1 = "Python is a programming language and python language is preferable for Data Science"
text2 = "Oyhton is used for Machine Learning"
text3 = "Pyhton is used for Deep Learning"



In [2]:
from nltk.corpus import stopwords


In [3]:
stopwords.words("english")

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - 'C:\\Users\\abhis/nltk_data'
    - 'c:\\Users\\abhis\\AppData\\Local\\Programs\\Python\\Python311\\nltk_data'
    - 'c:\\Users\\abhis\\AppData\\Local\\Programs\\Python\\Python311\\share\\nltk_data'
    - 'c:\\Users\\abhis\\AppData\\Local\\Programs\\Python\\Python311\\lib\\nltk_data'
    - 'C:\\Users\\abhis\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [4]:
import nltk
nltk.download('stopwords')

[nltk_data] Error loading stopwords: Remote end closed connection
[nltk_data]     without response


False

In [6]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

import os
import glob
import re


Data gathering 

In [7]:
neg_folder_path = r"D:\abhi python\Python hands on\Python-Hands-ON\neg"
pos_folder_path = r"D:\abhi python\Python hands on\Python-Hands-ON\pos"


In [10]:
neg_folder_files=glob.glob(f"{neg_folder_path}\\*.txt")
len(neg_folder_files)

1010

In [11]:
pos_folder_files = glob.glob(f"{pos_folder_path}\\*.txt")
len(pos_folder_files)

999

In [21]:
review_list = []
for file_name in neg_folder_files:
    f=open(file_name,"r")
    text = f.read()
    text = re.sub("[^a-z]"," ",text.lower())
    review_list.append(text)
    

In [22]:
len(review_list)

1010

In [24]:
for file_name in pos_folder_files:
    f=open(file_name,"r")
    text = f.read()
    text = re.sub("[^a-z]"," ",text.lower())
    review_list.append(text)
    

In [25]:
len(review_list)

2009

In [26]:
len(pos_folder_files)

999

In [27]:
len(neg_folder_files)

1010

In [29]:
np.zeros(1010,dtype=int)

array([0, 0, 0, ..., 0, 0, 0])

In [30]:
neg_target = np.zeros(len(neg_folder_files),dtype=int)
len(neg_target)

1010

In [31]:
pos_target = np.ones(len(pos_folder_files),dtype=int)
len(pos_target)

999

In [33]:
y = np.append(neg_target,pos_target)
y = pd.Series(y)
y

0       0
1       0
2       0
3       0
4       0
       ..
2004    1
2005    1
2006    1
2007    1
2008    1
Length: 2009, dtype: int32

Bag of Words

In [46]:
cnt_vector=CountVectorizer(stop_words="english",min_df=100)
x_xnt_vector=cnt_vector.fit_transform(review_list).toarray() 

In [47]:
x_cnt = pd.DataFrame(x_xnt_vector,columns=cnt_vector.get_feature_names_out())
x_cnt

ability  able  absolutely  act  acting  action  actor  actors  actress  \
0           0     0           0    0       0       0      0       1        0   
1           0     0           0    0       2       1      0       0        0   
2           0     0           0    0       1       0      0       0        0   
3           0     1           0    0       0       0      0       1        0   
4           0     0           0    0       0       0      2       0        0   
...       ...   ...         ...  ...     ...     ...    ...     ...      ...   
2004        0     0           0    0       1       0      0       0        0   
2005        0     0           0    0       0       0      1       0        0   
2006        1     0           0    0       0       3      0       0        0   
2007        0     0           0    0       0       0      1       2        0   
2008        0     0           0    0       0       0      0       0        0   

      actual  ...  writers  writing  written  wrong  wrote  year  years  yes  \
0          0  ...        0        0        0      0      0     0      1    0   
1          0  ...        0        0        0      0      0     0      0    0   
2          0  ...        0        0        1      1      0     0      0    0   
3          0  ...        0        0        0      0      0     1      0    0   
4          0  ...        0        0        0      0      0     0      0    0   
...      ...  ...      ...      ...      ...    ...    ...   ...    ...  ...   
2004       0  ...        0        1        1      0      0     3      0    0   
2005       0  ...        0        0        0      0      0     0      0    0   
2006       1  ...        0        0        0      0      1     0      0    0   
2007       0  ...        0        0        0      0      0     1      0    0   
2008       0  ...        0        0        1      0      0     0      0    0   

      york  young  
0        0      0  
1        0      0  
2        0      1  
3        0      0  
4        0      0  
...    ...    ...  
2004     0      0  
2005     0      0  
2006     0      2  
2007     0      0  
2008     0      0  

[2009 rows x 894 columns]

TF-IDF

In [49]:
tfidf_vector = TfidfVectorizer(stop_words="english",min_df=100)
x_tdf_vector = tfidf_vector.fit_transform(review_list).toarray()
x_tdf = pd.DataFrame(x_tdf_vector,columns=tfidf_vector.get_feature_names_out())
x_tdf

ability      able  absolutely  act    acting    action     actor  \
0     0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.000000   
1     0.00000  0.000000         0.0  0.0  0.164234  0.079635  0.000000   
2     0.00000  0.000000         0.0  0.0  0.056058  0.000000  0.000000   
3     0.00000  0.099575         0.0  0.0  0.000000  0.000000  0.000000   
4     0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.116198   
...       ...       ...         ...  ...       ...       ...       ...   
2004  0.00000  0.000000         0.0  0.0  0.040021  0.000000  0.000000   
2005  0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.103413   
2006  0.05045  0.000000         0.0  0.0  0.000000  0.090708  0.000000   
2007  0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.049302   
2008  0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.000000   

        actors  actress    actual  ...  writers   writing   written     wrong  \
0     0.049065      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
1     0.000000      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
2     0.000000      0.0  0.000000  ...      0.0  0.000000  0.066540  0.069025   
3     0.079827      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
4     0.000000      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
...        ...      ...       ...  ...      ...       ...       ...       ...   
2004  0.000000      0.0  0.000000  ...      0.0  0.059363  0.047505  0.000000   
2005  0.000000      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
2006  0.000000      0.0  0.050556  ...      0.0  0.000000  0.000000  0.000000   
2007  0.090333      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
2008  0.000000      0.0  0.000000  ...      0.0  0.000000  0.046012  0.000000   

         wrote      year     years  yes  york     young  
0     0.000000  0.000000  0.045707  0.0   0.0  0.000000  
1     0.000000  0.000000  0.000000  0.0   0.0  0.000000  
2     0.000000  0.000000  0.000000  0.0   0.0  0.057257  
3     0.000000  0.074309  0.000000  0.0   0.0  0.000000  
4     0.000000  0.000000  0.000000  0.0   0.0  0.000000  
...        ...       ...       ...  ...   ...       ...  
2004  0.000000  0.113128  0.000000  0.0   0.0  0.000000  
2005  0.000000  0.000000  0.000000  0.0   0.0  0.000000  
2006  0.051096  0.000000  0.000000  0.0   0.0  0.063691  
2007  0.000000  0.042044  0.000000  0.0   0.0  0.000000  
2008  0.000000  0.000000  0.000000  0.0   0.0  0.000000  

[2009 rows x 894 columns]

Train test split

In [50]:
x_train,x_test,y_train,y_test = train_test_split(x_tdf,y,test_size=0.2,random_state=24)

In [51]:
x_train

ability  able  absolutely  act    acting    action     actor    actors  \
1959      0.0   0.0    0.000000  0.0  0.062679  0.000000  0.000000  0.000000   
1553      0.0   0.0    0.000000  0.0  0.000000  0.047850  0.109034  0.000000   
1106      0.0   0.0    0.000000  0.0  0.000000  0.000000  0.000000  0.055083   
54        0.0   0.0    0.000000  0.0  0.000000  0.053319  0.060748  0.000000   
1355      0.0   0.0    0.000000  0.0  0.000000  0.000000  0.051989  0.000000   
...       ...   ...         ...  ...       ...       ...       ...       ...   
1425      0.0   0.0    0.000000  0.0  0.000000  0.000000  0.000000  0.000000   
343       0.0   0.0    0.000000  0.0  0.000000  0.000000  0.000000  0.000000   
192       0.0   0.0    0.000000  0.0  0.000000  0.000000  0.100482  0.046026   
899       0.0   0.0    0.000000  0.0  0.000000  0.000000  0.064110  0.000000   
418       0.0   0.0    0.088207  0.0  0.000000  0.056993  0.000000  0.059487   

       actress  actual  ...   writers  writing   written     wrong  wrote  \
1959  0.096077     0.0  ...  0.000000      0.0  0.000000  0.000000    0.0   
1553  0.000000     0.0  ...  0.000000      0.0  0.000000  0.000000    0.0   
1106  0.000000     0.0  ...  0.091399      0.0  0.064595  0.000000    0.0   
54    0.000000     0.0  ...  0.092341      0.0  0.000000  0.000000    0.0   
1355  0.000000     0.0  ...  0.000000      0.0  0.055852  0.057937    0.0   
...        ...     ...  ...       ...      ...       ...       ...    ...   
1425  0.000000     0.0  ...  0.000000      0.0  0.000000  0.000000    0.0   
343   0.000000     0.0  ...  0.000000      0.0  0.000000  0.000000    0.0   
192   0.000000     0.0  ...  0.000000      0.0  0.000000  0.000000    0.0   
899   0.000000     0.0  ...  0.000000      0.0  0.000000  0.000000    0.0   
418   0.000000     0.0  ...  0.000000      0.0  0.000000  0.000000    0.0   

          year     years  yes  york     young  
1959  0.000000  0.000000  0.0   0.0  0.000000  
1553  0.000000  0.000000  0.0   0.0  0.000000  
1106  0.000000  0.051314  0.0   0.0  0.000000  
54    0.000000  0.051843  0.0   0.0  0.056156  
1355  0.000000  0.044369  0.0   0.0  0.000000  
...        ...       ...  ...   ...       ...  
1425  0.074942  0.074998  0.0   0.0  0.081237  
343   0.000000  0.000000  0.0   0.0  0.000000  
192   0.000000  0.042876  0.0   0.0  0.000000  
899   0.164014  0.000000  0.0   0.0  0.000000  
418   0.000000  0.000000  0.0   0.0  0.000000  

[1607 rows x 894 columns]

Model training

* Gaussian naive Bias >> If data is continuous and normally distributed.
* Multinomial naive Bias >> It will accept dicsrete >> categorical
* Bernaoulli Naive Bias >> All data is in Binary 0 and 1

1. GaussianNB


In [52]:
gnb_model = GaussianNB()
gnb_model.fit(x_train, y_train)

GaussianNB()

Evaluation on Testing Data

In [53]:
y_pred_test = gnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("COnfusion matrix :\n",cnf_matrix)
clf_report=classification_report(y_test, y_pred_test)
print("Classification report:\n",clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuarcy: ",accuracy)

COnfusion matrix :
 [[147  45]
 [ 60 150]]
Classification report:
               precision    recall  f1-score   support

           0       0.71      0.77      0.74       192
           1       0.77      0.71      0.74       210

    accuracy                           0.74       402
   macro avg       0.74      0.74      0.74       402
weighted avg       0.74      0.74      0.74       402

Accuarcy:  0.7388059701492538


Evaluation on TRaining data 

In [54]:
y_pred_train = gnb_model.predict(x_train)
cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("Confusion matrix: ",cnf_matrix)
clf_report=classification_report(y_train,y_pred_train)
print("CLassfifcation report:\n",clf_report )
accuracy=accuracy_score(y_train,y_pred_train)
print("Accuracy: ",accuracy)

Confusion matrix:  [[716 102]
 [110 679]]
CLassfifcation report:
               precision    recall  f1-score   support

           0       0.87      0.88      0.87       818
           1       0.87      0.86      0.86       789

    accuracy                           0.87      1607
   macro avg       0.87      0.87      0.87      1607
weighted avg       0.87      0.87      0.87      1607

Accuracy:  0.8680771624144369


2.MultinomialNB

In [55]:
mnb_model = MultinomialNB()
mnb_model.fit(x_train, y_train)

MultinomialNB()

Evaluation on Testing data

In [57]:
y_pred_test = mnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("COnfusion matrix :\n",cnf_matrix)
clf_report=classification_report(y_test, y_pred_test)
print("Classification report:\n",clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuarcy: ",accuracy)

COnfusion matrix :
 [[156  36]
 [ 51 159]]
Classification report:
               precision    recall  f1-score   support

           0       0.75      0.81      0.78       192
           1       0.82      0.76      0.79       210

    accuracy                           0.78       402
   macro avg       0.78      0.78      0.78       402
weighted avg       0.79      0.78      0.78       402

Accuarcy:  0.7835820895522388


Evaluation on Training Data

In [58]:
y_pred_train = mnb_model.predict(x_train)
cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("Confusion matrix: ",cnf_matrix)
clf_report=classification_report(y_train,y_pred_train)
print("CLassfifcation report:\n",clf_report )
accuracy=accuracy_score(y_train,y_pred_train)
print("Accuracy: ",accuracy)

Confusion matrix:  [[718 100]
 [134 655]]
CLassfifcation report:
               precision    recall  f1-score   support

           0       0.84      0.88      0.86       818
           1       0.87      0.83      0.85       789

    accuracy                           0.85      1607
   macro avg       0.86      0.85      0.85      1607
weighted avg       0.85      0.85      0.85      1607

Accuracy:  0.8543870566272558


3.BernoulliNB

In [59]:
bnb_model = BernoulliNB()
bnb_model.fit(x_train, y_train)

BernoulliNB()

Evaluation on testing data

In [60]:
y_pred_test = bnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("COnfusion matrix :\n",cnf_matrix)
clf_report=classification_report(y_test, y_pred_test)
print("Classification report:\n",clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuarcy: ",accuracy)

COnfusion matrix :
 [[156  36]
 [ 51 159]]
Classification report:
               precision    recall  f1-score   support

           0       0.75      0.81      0.78       192
           1       0.82      0.76      0.79       210

    accuracy                           0.78       402
   macro avg       0.78      0.78      0.78       402
weighted avg       0.79      0.78      0.78       402

Accuarcy:  0.7835820895522388


Evalaution on training data

In [61]:
y_pred_train = bnb_model.predict(x_train)
cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("Confusion matrix: ",cnf_matrix)
clf_report=classification_report(y_train,y_pred_train)
print("CLassfifcation report:\n",clf_report )
accuracy=accuracy_score(y_train,y_pred_train)
print("Accuracy: ",accuracy)

Confusion matrix:  [[717 101]
 [150 639]]
CLassfifcation report:
               precision    recall  f1-score   support

           0       0.83      0.88      0.85       818
           1       0.86      0.81      0.84       789

    accuracy                           0.84      1607
   macro avg       0.85      0.84      0.84      1607
weighted avg       0.84      0.84      0.84      1607

Accuracy:  0.8438083385189795


* Large dataset == No of rows >> no of columns
* High Dimensional dataset == No of columns >> No of rows 

* Natural Language Processing >> In terms of review >> For 1 review 1 row will be there

1. Naive Bayes 
2. Support Vector Machines

1. Naive Bayes 
* Bayes theorem 
* Sentiment Analysis
* Spam filteration 

* Bayes theorem >> Prob(A/B) = Prob(A) * Prob(B/A) / Prob(B)
* Probability of A given B >>> Probability A when B event is occured 
* Prob(A/B) = Prob(A) * Prob(B/A) / prob(B)
* Prob(Y/X) = Prob(Y) * Prob(X/Y) / prob(X)

* Multiple Independent varaibles 
> Prob(Y|{X1,X2}) = Prob(X1/Y) * Prob(X2/Y) * Prob(Y) / Prob(X1) * Prob(X2)

* posterier proablity = likelihood Proablity * Prior probability / Marginal probability
* Prob(Y|{X1,X2,X3}) = Prob(Y) * Prob(X1/Y) * Prob(X2/Y) * Prob(X3/Y) / Prob(X1) * Prob(X2) * Prob(X3)

* NLP >> Natural Language processing 
* nltk >> natural language 

1. Bag of Words >> Used to covert text to numeric data 
text1 = "Python is programming language and Python language is preferble for data science"
text2 = "Python is used for machine learning"
text3 = "Python is used for Deep learning"

       Python   programming  language  preferble  data  science  used  machine  learning Deep
text1    2          1            2        1         1       1      0     0          0      0

text2    1          0            0        0         0       0      1     1          1      0

text3    1          0            0        0         0       0      1     0          1      1

2. TF - IDF  >> Term Frequency and Inverse document frequency
* term >> Word
* TF >> Value , IDF >> Values , TF * IDF >> TF-IDF vector 
* Term Frequency = (Count of word in the document) / (Total Number of words in the document)

text1 = "Python is programming language and Python language is preferble for data science"
text2 = "Python is used for machine learning"
text3 = "Python is used for Deep learning"

* TF >> Term Frequency 
       Python   programming  language  preferble  data  science  used  machine  learning Deep
        
text1   2/6       1/6          2/6       1/6       1/6   1/6       0     0          0      0

text2   1/4       0             0        0         0        0     1/4    1/4      1/4      0

text3   1/4       0             0        0         0        0      1/4     0       1/4     1/4

* IDF >> Inverse document frequency
* IDF == Log[(Number of documents) / (Number of documents containing the term)]


* TF * IDF 
       Python   programming  language  preferble  data  science  used  machine  learning Deep
        
text1    0        0.18         0.36      0.18      0.18   0.18     0      0          0      0

text2    0       0             0        0         0        0      0.1     0.27      0.1      0

text3    0       0             0        0         0        0      0.1       0       0.1     0.27

* BOW 
       Python   programming  language  preferble  data  science  used  machine  learning Deep
text1    2          1            2        1         1       1      0     0          0      0

text2    1          0            0        0         0        0     1     1          1      0

text3    1          0            0        0         0        0     1     0          1      1



In [63]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

import os 
import glob
import re

Data Gathering 

In [64]:
neg_folder_path = r"D:\abhi python\Python hands on\Python-Hands-ON\neg"
pos_folder_path = r"D:\abhi python\Python hands on\Python-Hands-ON\pos"


In [65]:
neg_folder_files = glob.glob(f"{neg_folder_path}\\*.txt")
len(neg_folder_files)

1010

In [66]:
pos_folder_files = glob.glob(f"{pos_folder_path}\\*.txt")
len(pos_folder_files)

999

In [67]:
review_list = []
for file_name in neg_folder_files:
    f=open(file_name,"r")
    text = f.read()
    text = re.sub("[^a-z]"," ",text.lower())
    review_list.append(text)

In [68]:
for file_name in pos_folder_files:
    f=open(file_name,"r")
    text = f.read()
    text = re.sub("[^a-z]"," ",text.lower())
    review_list.append(text)

In [69]:
len(review_list)

2009

In [70]:
len(pos_folder_files)

999

In [71]:
len(neg_folder_files)

1010

In [72]:
neg_target = np.zeros(len(neg_folder_files),dtype=int)
pos_target = np.ones(len(pos_folder_files),dtype=int)


In [73]:
y = np.append(neg_target,pos_target)
y = pd.Series(y)
y

0       0
1       0
2       0
3       0
4       0
       ..
2004    1
2005    1
2006    1
2007    1
2008    1
Length: 2009, dtype: int32

Bag of Words 

In [74]:
cnt_vector = CountVectorizer(stop_words="english",min_df=100)
x_xnt_vector = cnt_vector.fit_transform(review_list).toarray()
x_cnt = pd.DataFrame(x_xnt_vector,columns=cnt_vector.get_feature_names_out())
x_cnt

ability  able  absolutely  act  acting  action  actor  actors  actress  \
0           0     0           0    0       0       0      0       1        0   
1           0     0           0    0       2       1      0       0        0   
2           0     0           0    0       1       0      0       0        0   
3           0     1           0    0       0       0      0       1        0   
4           0     0           0    0       0       0      2       0        0   
...       ...   ...         ...  ...     ...     ...    ...     ...      ...   
2004        0     0           0    0       1       0      0       0        0   
2005        0     0           0    0       0       0      1       0        0   
2006        1     0           0    0       0       3      0       0        0   
2007        0     0           0    0       0       0      1       2        0   
2008        0     0           0    0       0       0      0       0        0   

      actual  ...  writers  writing  written  wrong  wrote  year  years  yes  \
0          0  ...        0        0        0      0      0     0      1    0   
1          0  ...        0        0        0      0      0     0      0    0   
2          0  ...        0        0        1      1      0     0      0    0   
3          0  ...        0        0        0      0      0     1      0    0   
4          0  ...        0        0        0      0      0     0      0    0   
...      ...  ...      ...      ...      ...    ...    ...   ...    ...  ...   
2004       0  ...        0        1        1      0      0     3      0    0   
2005       0  ...        0        0        0      0      0     0      0    0   
2006       1  ...        0        0        0      0      1     0      0    0   
2007       0  ...        0        0        0      0      0     1      0    0   
2008       0  ...        0        0        1      0      0     0      0    0   

      york  young  
0        0      0  
1        0      0  
2        0      1  
3        0      0  
4        0      0  
...    ...    ...  
2004     0      0  
2005     0      0  
2006     0      2  
2007     0      0  
2008     0      0  

[2009 rows x 894 columns]

2. TF - IDF 

In [75]:
tfidf_vector = TfidfVectorizer(stop_words="english",min_df=100)
x_tdf_vector = tfidf_vector.fit_transform(review_list).toarray()
x_tdf = pd.DataFrame(x_tdf_vector,columns=tfidf_vector.get_feature_names_out())
x_tdf

ability      able  absolutely  act    acting    action     actor  \
0     0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.000000   
1     0.00000  0.000000         0.0  0.0  0.164234  0.079635  0.000000   
2     0.00000  0.000000         0.0  0.0  0.056058  0.000000  0.000000   
3     0.00000  0.099575         0.0  0.0  0.000000  0.000000  0.000000   
4     0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.116198   
...       ...       ...         ...  ...       ...       ...       ...   
2004  0.00000  0.000000         0.0  0.0  0.040021  0.000000  0.000000   
2005  0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.103413   
2006  0.05045  0.000000         0.0  0.0  0.000000  0.090708  0.000000   
2007  0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.049302   
2008  0.00000  0.000000         0.0  0.0  0.000000  0.000000  0.000000   

        actors  actress    actual  ...  writers   writing   written     wrong  \
0     0.049065      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
1     0.000000      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
2     0.000000      0.0  0.000000  ...      0.0  0.000000  0.066540  0.069025   
3     0.079827      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
4     0.000000      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
...        ...      ...       ...  ...      ...       ...       ...       ...   
2004  0.000000      0.0  0.000000  ...      0.0  0.059363  0.047505  0.000000   
2005  0.000000      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
2006  0.000000      0.0  0.050556  ...      0.0  0.000000  0.000000  0.000000   
2007  0.090333      0.0  0.000000  ...      0.0  0.000000  0.000000  0.000000   
2008  0.000000      0.0  0.000000  ...      0.0  0.000000  0.046012  0.000000   

         wrote      year     years  yes  york     young  
0     0.000000  0.000000  0.045707  0.0   0.0  0.000000  
1     0.000000  0.000000  0.000000  0.0   0.0  0.000000  
2     0.000000  0.000000  0.000000  0.0   0.0  0.057257  
3     0.000000  0.074309  0.000000  0.0   0.0  0.000000  
4     0.000000  0.000000  0.000000  0.0   0.0  0.000000  
...        ...       ...       ...  ...   ...       ...  
2004  0.000000  0.113128  0.000000  0.0   0.0  0.000000  
2005  0.000000  0.000000  0.000000  0.0   0.0  0.000000  
2006  0.051096  0.000000  0.000000  0.0   0.0  0.063691  
2007  0.000000  0.042044  0.000000  0.0   0.0  0.000000  
2008  0.000000  0.000000  0.000000  0.0   0.0  0.000000  

[2009 rows x 894 columns]

Train Test Split 

In [76]:
x_train,x_test,y_train,y_test = train_test_split(x_tdf,y,test_size=0.2,random_state=24)


Model Training 

* Gaussian Naive Bayes >> If the data is continuous and normally distributed
* Multinomial Naive Bayes >> It will accept discrete i.e Categorical 
* Bernoulli Naive Bayes >> All data is in Binary 0 and 1


1. GaussianNB

In [77]:
gnb_model = GaussianNB()
gnb_model.fit(x_train, y_train)

GaussianNB()

Testing Data Evaluation 

In [78]:
y_pred_test = gnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("COnfusion matrix :\n",cnf_matrix)
clf_report=classification_report(y_test, y_pred_test)
print("Classification report:\n",clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuarcy: ",accuracy)

COnfusion matrix :
 [[147  45]
 [ 60 150]]
Classification report:
               precision    recall  f1-score   support

           0       0.71      0.77      0.74       192
           1       0.77      0.71      0.74       210

    accuracy                           0.74       402
   macro avg       0.74      0.74      0.74       402
weighted avg       0.74      0.74      0.74       402

Accuarcy:  0.7388059701492538


Training data evaluation 

In [79]:
y_pred_train = gnb_model.predict(x_train)
cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("Confusion matrix: ",cnf_matrix)
clf_report=classification_report(y_train,y_pred_train)
print("CLassfifcation report:\n",clf_report )
accuracy=accuracy_score(y_train,y_pred_train)
print("Accuracy: ",accuracy)

Confusion matrix:  [[716 102]
 [110 679]]
CLassfifcation report:
               precision    recall  f1-score   support

           0       0.87      0.88      0.87       818
           1       0.87      0.86      0.86       789

    accuracy                           0.87      1607
   macro avg       0.87      0.87      0.87      1607
weighted avg       0.87      0.87      0.87      1607

Accuracy:  0.8680771624144369


2. MultinomialNB

In [80]:
mnb_model = MultinomialNB()
mnb_model.fit(x_train, y_train)

MultinomialNB()

Testing data evaluation 

In [81]:
y_pred_test = mnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("COnfusion matrix :\n",cnf_matrix)
clf_report=classification_report(y_test, y_pred_test)
print("Classification report:\n",clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuarcy: ",accuracy)

COnfusion matrix :
 [[156  36]
 [ 51 159]]
Classification report:
               precision    recall  f1-score   support

           0       0.75      0.81      0.78       192
           1       0.82      0.76      0.79       210

    accuracy                           0.78       402
   macro avg       0.78      0.78      0.78       402
weighted avg       0.79      0.78      0.78       402

Accuarcy:  0.7835820895522388


TRaining data evalution 

In [82]:
y_pred_train = mnb_model.predict(x_train)
cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("Confusion matrix: ",cnf_matrix)
clf_report=classification_report(y_train,y_pred_train)
print("CLassfifcation report:\n",clf_report )
accuracy=accuracy_score(y_train,y_pred_train)
print("Accuracy: ",accuracy)

Confusion matrix:  [[718 100]
 [134 655]]
CLassfifcation report:
               precision    recall  f1-score   support

           0       0.84      0.88      0.86       818
           1       0.87      0.83      0.85       789

    accuracy                           0.85      1607
   macro avg       0.86      0.85      0.85      1607
weighted avg       0.85      0.85      0.85      1607

Accuracy:  0.8543870566272558


3. BernoulliNB

In [83]:
bnb_model = BernoulliNB()
bnb_model.fit(x_train, y_train)

BernoulliNB()

Testing data evaluation

In [84]:
y_pred_test = bnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("COnfusion matrix :\n",cnf_matrix)
clf_report=classification_report(y_test, y_pred_test)
print("Classification report:\n",clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuarcy: ",accuracy)

COnfusion matrix :
 [[156  36]
 [ 51 159]]
Classification report:
               precision    recall  f1-score   support

           0       0.75      0.81      0.78       192
           1       0.82      0.76      0.79       210

    accuracy                           0.78       402
   macro avg       0.78      0.78      0.78       402
weighted avg       0.79      0.78      0.78       402

Accuarcy:  0.7835820895522388


Training data evaluation

In [85]:
y_pred_train = bnb_model.predict(x_train)
cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("Confusion matrix: ",cnf_matrix)
clf_report=classification_report(y_train,y_pred_train)
print("CLassfifcation report:\n",clf_report )
accuracy=accuracy_score(y_train,y_pred_train)
print("Accuracy: ",accuracy)

Confusion matrix:  [[717 101]
 [150 639]]
CLassfifcation report:
               precision    recall  f1-score   support

           0       0.83      0.88      0.85       818
           1       0.86      0.81      0.84       789

    accuracy                           0.84      1607
   macro avg       0.85      0.84      0.84      1607
weighted avg       0.84      0.84      0.84      1607

Accuracy:  0.8438083385189795
