In [1]:
import re 
string = "Python and Machine Learning 7741 is syllabus of Data Science."
string2 = re.findall("[a-zA-Z0-9]",string)
if string2:
    print("String contains character")
else:
    print("String not contains characters")

String contains character


In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [3]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"is",string)
result

['Python and Machine Learning ',
 ' syllabus of data science and deep learning.']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [7]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s{1}\d{2}\b",sample_string)
result

['123 45', '678 90']

In [10]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [11]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
if result:
    print("String is present.")
else:
    print("String is not present.")

String is present.


In [12]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
if result:
    print("String is present.")
else:
    print("String is not present.")

String is present.


In [13]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [14]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [15]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"[b]{3}",str1)
result

['bbb', 'bbb']

In [16]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"[b]{2,3}",str1)
result

['bbb', 'bbb', 'bb']

In [17]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"[b]{2,3}",str1)
result

['bbb', 'bbb', 'bb']

In [18]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [19]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [21]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [22]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [23]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [24]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [25]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [26]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\bS.+e\b",str1)
result

['Science']

In [27]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall("Suceess",str1)
result

['Suceess']

In [28]:
str1 = 'new begening of LIFE .'
result = re.findall("LIFE.",str1)
result

['LIFE ']

In [29]:
str1 = 'new begening of LIFE .'
result = re.findall("LIFE.",str1)
result

['LIFE ']

In [32]:
str1 = "today is the very lazy day"
result = re.findall(r"\b\w.z\w\b",str1)
result

['lazy']

In [33]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y].z[a-y]",str1)
result

['lazy']

In [34]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [35]:
str1 = "9821 maya"
result = re.findall(r"^9",str1)
result

['9']

In [41]:
str1 = "9821 maya"
result = re.findall(r"^9....",str1)
result

['9821 ']

In [42]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [44]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [45]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d\b",str1)
result

['3', '2']

In [49]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\d+",str1)
result

['1', '12', '13', '345']

In [50]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for i in Searched_words:
    result = re.findall(i , Sample_text)
    print(result)

['fox']
['dog']
[]


In [51]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search("fox",sample_text)
print(f"start index is {result.start()} and end index is {result.end()}")

start index is 16 and end index is 19


In [52]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search("dog",sample_text)
print(f"start index is {result.start()} and end index is {result.end()}")

start index is 40 and end index is 43


In [53]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [54]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print("Occurence of the strings:",len(result))
result = re.search(r"exercises",Sample_text)
print(f"The position of the substring starts from {result.start()} and end is {result.end()}")


Occurence of the strings: 3
The position of the substring starts from 7 and end is 16


In [55]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"\s","_",str1)
result

'The_quick_brown_fox_jumps_over_the_lazy_dog.'

In [57]:
result = re.sub(r"[_]","[ ]",str1)
result

'The quick brown fox jumps over the lazy dog.'

In [58]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [59]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [61]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*\b",str1)
result

['and', 'every', 'evening']

In [62]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [63]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[., ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [64]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [65]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [66]:
text ="""Python is a general purpose interpreted."""
result = re.sub(r"[ ]+", " ",text)
result

'Python is a general purpose interpreted.'

In [1]:
import numpy as np
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
import numpy as np
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
arr1[4] = 1 
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [7]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = list(reversed(arr1))
arr2

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [10]:
arr1 = np.random.randint(10,20,size=(2,2))
print("array 1 :\n",arr1)
arr2 = np.random.randint(40,50,size=(2,2))
print("array 2 :\n",arr2)

array 1 :
 [[15 13]
 [12 11]]
array 2 :
 [[49 49]
 [41 44]]


In [11]:
add = arr1 + arr2
add

array([[64, 62],
       [53, 55]])

In [12]:
sub1 = arr1 - arr2
sub1

array([[-34, -36],
       [-29, -33]])

In [13]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [14]:
import math
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [15]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [16]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
mean_row = np.mean(arr1 , axis=1)
print("Mean across row >>",mean_row)
mean_col = np.mean(arr1 , axis=0)
print("Mean across col >>",mean_col)

Mean across row >> [2. 5. 8.]
Mean across col >> [4. 5. 6.]


In [18]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [19]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1[:: , ::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [22]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [24]:
arr1 = np.array([1,2,0,0,4,0])
arr1

array([1, 2, 0, 0, 4, 0])

In [25]:
result = np.nonzero(arr1)
result

(array([0, 1, 4], dtype=int64),)

In [26]:
arr1 = np.array([[1,2],[3,4]])
print("Matrix :\n",arr1)
result = np.linalg.det(arr1)
print("Determinant:",result)

Matrix :
 [[1 2]
 [3 4]]
Determinant: -2.0000000000000004


In [27]:
arr1 

array([[1, 2],
       [3, 4]])

In [28]:
result = np.linalg.inv(arr1)
print("Inverse :\n",result)

Inverse :
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
arr1 = np.random.randint(10,30,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
print("Mean of the array:",result)

Array:
 [16 27 10 22 27 14 12 16 11 26 19 26 12 28 23 14 26 11 24 26 14 22 11 15
 24 21 17 21 22 21]
Mean of the array: 19.266666666666666


In [30]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
arr2 = np.where(arr1 > 5)
arr2

Array: [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [31]:
arr1 = np.random.random((3,3,3))
print("Array:\n",arr1)

Array:
 [[[0.25312914 0.77275225 0.26439383]
  [0.28118116 0.19979356 0.27012916]
  [0.21612571 0.93182849 0.09867198]]

 [[0.97046811 0.46970908 0.52940651]
  [0.17963653 0.23640608 0.21051786]
  [0.10820511 0.77828061 0.49770822]]

 [[0.24067704 0.57612186 0.08294586]
  [0.10039204 0.46102535 0.7845512 ]
  [0.78896331 0.3342828  0.19273381]]]


In [32]:
arr1 = np.random.rand(10,10)
print("Array:",arr1)
print("Maximum Value :",np.max(arr1))
print("Minimum Value :",np.min(arr1))

Array: [[0.84601887 0.07729925 0.01647789 0.91111927 0.75959341 0.80149495
  0.72156763 0.45917844 0.92999173 0.64744862]
 [0.13597672 0.62321339 0.76117802 0.23481963 0.9733329  0.06718622
  0.63206375 0.64756631 0.46282206 0.51472993]
 [0.86476411 0.13787558 0.50899253 0.13245038 0.11713111 0.72576158
  0.63732242 0.12604181 0.88840562 0.89354191]
 [0.17896466 0.38027146 0.70639529 0.50979367 0.03867648 0.18299064
  0.20846516 0.86338375 0.91023927 0.31179254]
 [0.98077688 0.11877168 0.15079747 0.65581628 0.2719835  0.26919781
  0.42531902 0.07167277 0.47116335 0.44660103]
 [0.69885838 0.18966395 0.76924619 0.48628626 0.26860839 0.9309289
  0.00835771 0.00530895 0.56841055 0.68583775]
 [0.18132634 0.51979698 0.23139548 0.47361669 0.36130756 0.44482406
  0.32270146 0.1890044  0.63177142 0.24470769]
 [0.70706181 0.01308609 0.32890574 0.08728681 0.43317137 0.24794643
  0.78609316 0.4500617  0.59027253 0.0095614 ]
 [0.72181043 0.29551195 0.39278278 0.46619268 0.34659955 0.98044048
  0.31

In [33]:
arr1 = np.ones((10,10))
arr1[1:-1 , 1:-1] = 0 
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
arr1 = np.zeros((5,5) , dtype=int)
np.fill_diagonal(arr1[1:] , [1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [35]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:] , [1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [36]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1, arr2)
print("Array 1 :\n",arr1)
print("Array 2 :\n",arr2)
print("Multiplication array :\n",result)

Array 1 :
 [[2 4 4]
 [7 3 6]
 [4 8 5]
 [5 3 2]
 [7 3 5]]
Array 2 :
 [[8 6]
 [1 5]
 [6 3]]
Multiplication array :
 [[44 44]
 [95 75]
 [70 79]
 [55 51]
 [89 72]]


In [38]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
arr1[(arr1 >= 3) & (arr1 <= 8)] *= -1
arr1

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [39]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
arr2 = np.where((arr1 >= 3) & (arr1 <= 8) , -1*arr1 , arr1)
print("Array 1 :\n",arr1)
print("Array 2 :\n",arr2)

Array 1 :
 [ 1  2  3  4  5  6  7  8 44  9 33  6  5 10]
Array 2 :
 [ 1  2 -3 -4 -5 -6 -7 -8 44  9 33 -6 -5 10]


In [40]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Original array:\n",arr1)
print("New array:\n",np.around(arr1,1))

Original array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]
New array:
 [[1.2 2.7]
 [3.5 5.2]]


In [41]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
rounded_up = np.ceil(arr1)
rounded_down = np.floor(arr1)
print("Original array :" , arr1)
print("Rounded up :\n" , rounded_up)
print("Rounded down :\n" , rounded_down)

Original array : [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]
Rounded up :
 [[2. 3.]
 [4. 6.]]
Rounded down :
 [[1. 2.]
 [3. 5.]]


In [42]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
common = np.intersect1d(arr1 , arr2)
common

array([4, 5, 6])

In [43]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [44]:
arr1 = np.random.randint(1,10,size=10)
print("Original array :" , arr1)
arr2 = np.sort(arr1)
print("Sorted array :" , arr2)

Original array : [5 1 3 9 6 6 4 4 4 2]
Sorted array : [1 2 3 4 4 4 5 6 6 9]


In [47]:
arr1 = np.zeros((5,5))
print("Original array :\n" , arr1)
arr2 = arr1 + np.arange(5)
print("New array:\n",arr2)

Original array :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
New array:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [48]:
arr1 = np.zeros((5,5))
print("New array :\n", arr1)
arr2 = arr1 + np.arange(5)
print("New array :\n", arr2)

New array :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
New array :
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [49]:
arr1 = np.random.randint(0,5,size=(5))
arr2 = np.random.randint(0,5,size=(5))
if np.equal == True:
    print("Both array are equal.")
else:
    print("Both arrays are not equal.")

Both arrays are not equal.


In [50]:
arr1 = np.random.randint(0,5,size=(5))
arr2 = np.random.randint(0,5,size=(5))
if np.equal == True:
    print("Both arrays are equal.")
else:
    print("Both arrays are not equal.")

Both arrays are not equal.


In [51]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
arr1[arr1.argmax()] = 0 
print("Maximum replaced by 0.:\n", arr1)


Array: [2 9 1 4 8 1 1 8 6 1]
Maximum replaced by 0.:
 [2 0 1 4 8 1 1 8 6 1]


In [52]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
arr1[arr1.argmax()] = 0
print("Maximum replaced by 0.:\n", arr1)

Array: [2 5 9 7 8 9 9 5 5 4]
Maximum replaced by 0.:
 [2 5 0 7 8 9 9 5 5 4]


In [53]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i , end=" ")

1 2 3 4 5 6 7 8 9 

In [54]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i ,end=" ")

1 2 3 4 5 6 7 8 9 

In [55]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [56]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [57]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array :\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array :
 [[6 2 4]
 [7 5 7]
 [7 9 4]]


array([[6, 2, 4],
       [7, 9, 4],
       [7, 5, 7]])

In [58]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array :\n",arr1)
arr1[[0,1]] = arr1[[1,0]]
arr1

Array :
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[5, 8, 9],
       [4, 3, 1],
       [3, 4, 5]])

In [59]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
arr1[[0,1]] = arr1[[1,0]]
arr1

array([[5, 8, 9],
       [4, 3, 1],
       [3, 4, 5]])

In [60]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [61]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.median(arr1)
result

5.5

In [62]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.std(arr1)
result

[1 1 9 8 2 9 2 1 3 3]


3.2078029864690882

In [63]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [64]:
result = np.around(5.43422 , 3)
result

5.434

In [65]:
arr1 = np.array([[2,3],[3,4]])
print(arr1)
result = np.linalg.inv(arr1)
result

[[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [66]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [67]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)[0]
result

6

In [68]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)[0]
result

6

In [69]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print("Dimension of the array:",arr1.ndim)
arr1.shape
arr2 = np.reshape(arr1 , (2,5,1))
arr2

[ 1  2  3  4  5  6  7  8  9 10]
Dimension of the array: 1


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [70]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print(arr1)
print("Dimension of the array:",arr1.ndim)
arr2 = np.reshape(arr1 , (6,4))
arr2

[[[[ 9 19 13 12]
   [16 11  1 10]
   [19 19 18 18]]

  [[ 5 15  8 15]
   [ 1 13 19 19]
   [ 2 19  2 19]]]]
Dimension of the array: 4


array([[ 9, 19, 13, 12],
       [16, 11,  1, 10],
       [19, 19, 18, 18],
       [ 5, 15,  8, 15],
       [ 1, 13, 19, 19],
       [ 2, 19,  2, 19]])

In [71]:
arr1 = np.zeros(10 , dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Matrix :\n",arr1)
print("Shape of the matrix:",arr1.shape)

Matrix :
 [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]
Shape of the matrix: (3, 4)
