In [ ]:
from collections import OrderedDict
dict1 = {'ravi': '10', 'rajnish': '9',
        'sanjeev': '15', 'yash': '2', 'suraj': '32'}
result = OrderedDict()

In [1]:
key_value={'l':11,'o':89,'a':88,'d':42,'p':5}
result = dict(sorted(key_value.items()))
result

{'a': 88, 'd': 42, 'l': 11, 'o': 89, 'p': 5}

In [2]:
key_value={'l':11,'o':89,'a':88,'d':42,'p':5}
result = dict(sorted(key_value.items()))
result

{'a': 88, 'd': 42, 'l': 11, 'o': 89, 'p': 5}

In [3]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
result = dict(sorted(dt.items(),key=lambda x : x[1]))
result

{'cc': 3, 'bb': 6, 'dd': 12, 'aa': 44}

In [4]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
result = dict(sorted(dt.items(),key=lambda x : x[1]))
result

{'cc': 3, 'bb': 6, 'dd': 12, 'aa': 44}

In [5]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
result = dt.values()
sum(result)

65

In [6]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
sum1 = 0 
for i in dt.values():
    sum1 += i
sum1 


65

In [7]:
test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
del test_dict["Arushi"]
test_dict

{'Mani': 21, 'Haritha': 21}

In [8]:
test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
del test_dict["Mani"]
test_dict

{'Arushi': 22, 'Haritha': 21}

In [9]:
test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
test_dict.pop("Arushi")

22

In [10]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
result = {**d1,**d2}
result

{'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32,
 'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12}

In [11]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
result = {**d2,**d1}
result

{'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12,
 'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32}

In [12]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
d1.update(d2)
d1

{'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32,
 'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12}

In [14]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
d2.update(d1)
d2

{'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12,
 'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32}

In [15]:
def calc(percent):
    if percent >= 90:
        return "A+"
    elif 80 <= percent < 90:
        return "A"
    elif 70 <= percent < 80:
        return "B"
    elif 60 <= percent < 70:
        return "C"
    elif 50 <= percent < 60:
        return "D"
    else:
        return "Fail"
    
def main():
    total_marks = 0 
    no_of_subjects = int(input("Enter the number of subjects:"))

    for i in range(no_of_subjects):
        marks = eval(input("Enter the marks of the subject:"))
        total_marks += marks

    average_percent = total_marks / no_of_subjects
    grade = calc(average_percent)
    print(f"Percentage recieved by the student is : {average_percent}")
    print(f"Grade recieved by Student is :{grade}")

if __name__ == "__main__":
    main()

Percentage recieved by the student is : 76.66666666666667
Grade recieved by Student is :B


In [17]:
words = ["listen", "silent", "enlist", "hello", "world", "act", "cat", "dog", "god"]
anagram_dict = {}
for word in words:
    sorted_word = " ".join(sorted(word))

    if sorted_word in anagram_dict:
        anagram_dict[sorted_word].append(word)
    else:
        anagram_dict[sorted_word] = [word]
anagram_dict

{'e i l n s t': ['listen', 'silent', 'enlist'],
 'e h l l o': ['hello'],
 'd l o r w': ['world'],
 'a c t': ['act', 'cat'],
 'd g o': ['dog', 'god']}

In [18]:
words = ["listen", "silent", "enlist", "hello", "world", "act", "cat", "dog", "god"]
anagram_dict = {}
for word in words:
    sorted_word = " ".join(sorted(word))

    if sorted_word in anagram_dict:
        anagram_dict[sorted_word].append(word)
    else:
        anagram_dict[sorted_word] = [word]
anagram_dict

{'e i l n s t': ['listen', 'silent', 'enlist'],
 'e h l l o': ['hello'],
 'd l o r w': ['world'],
 'a c t': ['act', 'cat'],
 'd g o': ['dog', 'god']}

In [19]:
def check_bin(num1,num2):
    binary_1 = bin(num1)[2:]
    binary_2 = bin(num2)[2:]

    return sorted(binary_1) == sorted(binary_2)

num1 = 10 
num2 = 10
if check_bin(num1,num2):
    print(f"The binary representation of {num1} and {num2} are anagrams")
else:
    print(f"The binary representation of {num1} and {num2} are not anagram")

The binary representation of 10 and 10 are anagrams


In [20]:
from collections import Counter
def largest(words):
    words_count = Counter("".join(sorted(word)) for word in words)
    result = max(words_count.values(),default=0)
    return result

word_list = ["listen", "silent", "enlist", "dog", "god", "good"]
final = largest(word_list)
final

3

In [21]:
from collections import Counter
def largest(words):
    words_count = Counter("".join(sorted(word)) for word in words)
    result = max(words_count.values(),default=0)
    return result

word_list = ["listen", "silent", "enlist", "dog", "god", "good"]
final = largest(word_list)
final

3

In [22]:
freq = {}
list1 = [1, 1, 1, 5, 5, 3, 1, 3, 3, 1,4, 4, 4, 2, 2, 2, 2]
for i in list1:
    if i in freq:
        freq[i] += 1
    else:
        freq[i] = 1
freq

{1: 5, 5: 2, 3: 3, 4: 3, 2: 4}

In [23]:
freq = {}
list1 = [1, 1, 1, 5, 5, 3, 1, 3, 3, 1,4, 4, 4, 2, 2, 2, 2]
for i in list1:
    if i in freq:
        freq[i] += 1
    else:
        freq[i] = 1
freq

{1: 5, 5: 2, 3: 3, 4: 3, 2: 4}

In [24]:
tups = [("akash", 10), ("gaurav", 12), ("anand", 14), 
    ("suraj", 20), ("akhil", 25), ("ashish", 30)]
result = dict(tups)
result

{'akash': 10,
 'gaurav': 12,
 'anand': 14,
 'suraj': 20,
 'akhil': 25,
 'ashish': 30}

In [25]:
numbers = [2, 3, 4, 5, 6]

result = [(num ** 2) for num in numbers]
result

[4, 9, 16, 25, 36]

In [26]:
numbers = [2, 3, 4, 5, 6]

result = [(num ** 3) for num in numbers]
result

[8, 27, 64, 125, 216]

In [27]:
tuples_list = [(2, 8), (3, 27), (1, 1), (5, 125), (4, 64)]

result = dict(sorted(tuples_list, key=lambda x : x[1]))
result

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}

In [28]:
tuples_list = [(2, 8), (3, 27), (1, 1), (5, 125), (4, 64)]

result = dict(sorted(tuples_list))
result

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}

In [4]:
subject_marks = [("English",88) , ("Science",90) , ("Maths",97) , ("Social sciences",82)]
result = sorted(subject_marks,key=lambda x : x[1])
result

[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

In [5]:
list1 = [{"name" : "Nandini" , "age" : 20} ,
        {"name" : "Manjeet" , "age" : 20} ,
        {"name" : "Nikhil" , "age" : 19}]
result = sorted(list1,key=lambda x : x["age"])
result

[{'name': 'Nikhil', 'age': 19},
 {'name': 'Nandini', 'age': 20},
 {'name': 'Manjeet', 'age': 20}]

In [6]:
list1 = [{"name" : "Nandini" , "age" : 20} ,
        {"name" : "Manjeet" , "age" : 20} ,
        {"name" : "Nikhil" , "age" : 19}]
result = sorted(list1,key=lambda x : x["name"])
result

[{'name': 'Manjeet', 'age': 20},
 {'name': 'Nandini', 'age': 20},
 {'name': 'Nikhil', 'age': 19}]

In [7]:
list1 = [{"name" : "Nandini" , "age" : 20} ,
        {"name" : "Manjeet" , "age" : 20} ,
        {"name" : "Nikhil" , "age" : 19}]
result = sorted(list1,key=lambda x : (x["age"],x["name"]))
result

[{'name': 'Nikhil', 'age': 19},
 {'name': 'Manjeet', 'age': 20},
 {'name': 'Nandini', 'age': 20}]

In [8]:
input_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = [(x**2) for x in input_numbers]
result

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [9]:
result = [(lambda x : x**2)(num) for num in input_numbers]
result

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [10]:
input_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = [(lambda x : x**3)(num) for num in input_numbers]
result

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [11]:
result = lambda x : True if x.startswith("P") else False 
print(result("Python"))

True


In [12]:
result = lambda x : True if x.startswith("M") else False
print(result("My"))

True


In [13]:
result = (lambda string : string.isdigit())(string = "1234")
result

True

In [14]:
result = (lambda string : string.isdecimal())(string = "1234")
result

True

In [15]:
result = (lambda string : string.isnumeric())(string = "1234")
result

True

In [16]:
import re
result = (lambda string : re.findall(r"[0-9]{1,}",string))(string = "1234")
result

['1234']

In [17]:
num = 9 
f1 = 0 
f2 = 1
print(f1,f2,end=" ")
for i in range(2,num):
    f3 = f1 + f2
    f1,f2 = f2,f3
    print(f3,end=" ")

0 1 1 2 3 5 8 13 21 

In [18]:
num = 9 
f1 = 0 
f2 = 1
print(f1,f2,end=" ")
for i in range(2,num):
    f3 = f1 + f2
    f1,f2 = f2,f3
    print(f3,end=" ")


0 1 1 2 3 5 8 13 21 

In [19]:
num = 5 
f1 = 0 
f2 = 1
print(f1,f2,end=" ")
for i in range(2,num):
    f3 = f1 + f2
    f1,f2 = f2,f3
    print(f3,end=" ")


0 1 1 2 3 

In [20]:
list1 = [1,2,3,4]
list2 = [3,4,5,6]
result = list(filter(lambda x : x in list1,list2))
result

[3, 4]

In [21]:
list1 = [1,2,3,4]
list2 = [3,4,5,6]
result = list(filter(lambda x : x in list2,list1))
result

[3, 4]

In [24]:
list1 = [-1,2,-3,5,7,8,9,-10]
result = lambda list1 : [x for x in list1 if x >= 0] + [x for x in list1 if x < 0]
result(list1)

[2, 5, 7, 8, 9, -1, -3, -10]

In [25]:
list1 = [-1,2,-3,5,7,8,9,-10]
result = lambda list1 : [x for x in list1 if x >= 0] + [x for x in list1 if x < 0]
result(list1)

[2, 5, 7, 8, 9, -1, -3, -10]

In [26]:
array_nums = [1,2,3,5,7,8,9,10]
odd = len(list(filter(lambda x : (x%2!=0),array_nums)))
even = len(list(filter(lambda x : (x%2==0),array_nums)))
odd

5

In [27]:
even

3

In [28]:
list1 = [1,2,3]
list2 = [4,5,6]
result = list(map(lambda x1,x2 : x1+x2,list1,list2))
result

[5, 7, 9]

In [29]:
list1 = [1,2,3]
list2 = [4,5,6]
result = list(map(lambda x1,x2 : x1+x2,list1,list2))
result

[5, 7, 9]

In [30]:
list1 = [13,26,38,39,57,15,17]
result = list(filter(lambda x : (x%13==0 or x%19==0),list1))
result

[13, 26, 38, 39, 57]

In [31]:
texts = ["php" , "w3r" , "Python" , "abcd" ,"Java" , "aaa"]
result = list(filter(lambda x : (x == "".join(reversed(x))),texts))
result

['php', 'aaa']

In [32]:
texts = ["php" , "w3r" , "Python" , "abcd" ,"Java" , "aaa"]
result = list(filter(lambda x : (x == "".join(reversed(x))),texts))
result

['php', 'aaa']

In [33]:
from collections import Counter
texts = ["bcda","abce","cbda","cbea","adcb"]
str1 = "abcd"
result = list(filter(lambda x : (Counter(str1) == Counter(x)),texts))
result

['bcda', 'cbda', 'adcb']

In [34]:
from collections import Counter
texts = ["bcda","abce","cbda","cbea","adcb"]
str1 = "abcd"
result = list(filter(lambda x : (Counter(str1) == Counter(x)),texts))
result

['bcda', 'cbda', 'adcb']

In [35]:
list1 = [2,3,4,5]
result = list(map(lambda x : x*5 , list1))
result

[10, 15, 20, 25]

In [37]:
list1 = [-1,-2,3,4]
positive = list(map(lambda list1 : list1 > 0 ,list1))
negative = list(map(lambda list1 : list1 < 0 ,list1))
sum(positive)

2

In [38]:
sum(negative)

2

In [41]:
list1 = [-1,-2,3,4]
positive = list(filter(lambda list1 : list1 > 0 ,list1))
negative = list(filter(lambda list1 : list1 < 0 ,list1))
sum(positive)

7

In [42]:
sum(negative)

-3

In [43]:
list1 = [[0],[1,3],[5,7],[9,11],[13,15,17]]
result = max(list1,key=lambda x : len(x))
result

[13, 15, 17]

In [44]:
list1 = [[0],[1,3],[5,7],[9,11],[13,15,17]]
result = min(list1 , key=lambda x : len(x))
result

[0]

In [45]:
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [2,4,6,8]
result = list(filter(lambda x : x not in list2,list1))
result

[1, 3, 5, 7, 9, 10]

In [46]:
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [2,4,6,8]
result = list(filter(lambda x : x not in list2,list1))
result

[1, 3, 5, 7, 9, 10]

In [49]:
tuple_str = (("223","ABCD","33") , ("1416","EFGH","55") , ("2345","WERT","34"))
result = tuple(map(lambda  x : (int(x[0]),int(x[2])),tuple_str))
result

((223, 33), (1416, 55), (2345, 34))

In [50]:
tuple_str = (("223","ABCD","33") , ("1416","EFGH","55") , ("2345","WERT","34"))
result = tuple(map(lambda x : (int(x[0]),int(x[2])),tuple_str))
result

((223, 33), (1416, 55), (2345, 34))

In [51]:
nums = [3,4,5,8,0,3,8,5,0,3,1,5,2,3,4,2]
result = dict(map(lambda x : (x , list(nums).count(x)),nums))
result

{3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

In [52]:
nums = [3,4,5,8,0,3,8,5,0,3,1,5,2,3,4,2]
result = dict(map(lambda x : (x,list(nums).count(x)),nums))
result

{3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

In [54]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
result = list(map(lambda x1,x2,x3 : x1+x2+x3,l1,l2,l3))
result

[12, 15, 18]

In [55]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
result = list(map(lambda x1,x2,x3 : x1+x2+x3,l1,l2,l3))
result

[12, 15, 18]

In [2]:
l1 = ["yellow","blue","tricolor"]
result = list(map(list,l1))
result

[['y', 'e', 'l', 'l', 'o', 'w'],
 ['b', 'l', 'u', 'e'],
 ['t', 'r', 'i', 'c', 'o', 'l', 'o', 'r']]

In [3]:
l1 = ["yellow","blue","tricolor"]
result = list(map(list,l1))
result

[['y', 'e', 'l', 'l', 'o', 'w'],
 ['b', 'l', 'u', 'e'],
 ['t', 'r', 'i', 'c', 'o', 'l', 'o', 'r']]

In [4]:
l1 = [12,15,18]
result = list(map(lambda x : x**2 , l1))
result

[144, 225, 324]

In [5]:
list1 = [1, 2, 3, 4, 5]
list2 = [5, 4, 3, 2, 1]
result = list(map(lambda x,y : x+y , list1, list2))
result

[6, 6, 6, 6, 6]

In [6]:
result = list(map(lambda x,y : x-y,list1,list2))
result

[-4, -2, 0, 2, 4]

In [7]:
int_list = [1, 2, 3, 4, 5]
result = list(map(lambda x : str(x),int_list))
result

['1', '2', '3', '4', '5']

In [8]:
int_tuple = (6, 7, 8, 9, 10)
result = list(map(lambda x : str(x),int_tuple))
result

['6', '7', '8', '9', '10']

In [9]:
num_array = [1, 2, 3, 4, 5]
result = sum(map(lambda x : x,num_array))
result

15

In [10]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 4, 8, 9]

result = sum(map(lambda x,y : x == y,list1,list2))
result

2

In [11]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 4, 8, 9]
result = sum(map(lambda x,y : x==y,list1,list2))
result

2

In [12]:
str1 = ["python","machine","learning"]
result = list(map(list,str1))
result

[['p', 'y', 't', 'h', 'o', 'n'],
 ['m', 'a', 'c', 'h', 'i', 'n', 'e'],
 ['l', 'e', 'a', 'r', 'n', 'i', 'n', 'g']]

In [13]:
str1 = ["python","machine","learning"]
result = list(map(list,str1))
result

[['p', 'y', 't', 'h', 'o', 'n'],
 ['m', 'a', 'c', 'h', 'i', 'n', 'e'],
 ['l', 'e', 'a', 'r', 'n', 'i', 'n', 'g']]

In [14]:
list_tup = [("python","machine"),("learning","data science")]
result = list(map(" ".join,list_tup))
result

['python machine', 'learning data science']

In [15]:
list_tup = [("python","machine"),("learning","data science")]
result = list(map(" ".join,list_tup))
result

['python machine', 'learning data science']

In [16]:
l1 = [1,2,3]
l2 = [1,2,4,5,6]
result = list(filter(lambda x : x not in l1,l2))
result

[4, 5, 6]

In [19]:
l1 = [1,2,3]
l2 = [1,2,4,5,6]
result = list(filter(lambda x : x not in l2,l1))
result

[3]

In [23]:
from nltk.corpus import stopwords
string = "Hi i am abhishek"
stopword_list = stopwords.words("english")
result = filter(lambda x : x.lower() not in stopword_list,string)
final = " ".join(result)
final

AttributeError: module 'nltk' has no attribute 'data'

In [24]:
l1 = [1,2,3]
l2 = [1,2,4,5,6]
result = list(filter(lambda x : x in l1,l2))
result

[1, 2]

In [25]:
l1 = [1,2,3]
result = list(filter(lambda x : (x%2!=0),l1))
result

[1, 3]

In [26]:
l1 = [1,2,3]
result = list(filter(lambda x : (x%2==0),l1))
result

[2]

In [1]:
with open("Abhishek1.txt") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [2]:
with open("Abhishek1.txt") as f:
    result = f.readline()
    print(result)

Data Science:



In [4]:
text = """1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing"""
with open("Abhishek1.txt","a") as f:
    f.write(text)
    f.close()


In [5]:
with open("Abhishek1.txt","r") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [6]:
with open("Abhishek1.txt","r") as f:
    result = f.read(-2)
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [8]:
with open("Abhishek1.txt","r") as f:
    result = f.readlines()
    print(result[-2:])

[' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [9]:
with open("Abhishek1.txt","r") as f:
    result = f.readlines()
    print(result)
    

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [10]:
with open("Abhishek1.txt","r") as f:
    result = f.readlines()
    print(len(result))

19


In [11]:
import shutil 
with open("Abhishek1.txt","r") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [12]:
with open("Abhishek1.txt","r") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [14]:
from datetime import datetime

current_datetime = datetime.now()
print("Current datetime :",current_datetime)

current_year = current_datetime.year
print("Current year :",current_year)

result = current_datetime.strftime("%B")
print("Month of the year:",result)

result = current_datetime.strftime("%U")
print("Week number of the year :",result)

result = current_datetime.strftime("%A")
print("Day of the year :",result)

result = current_datetime.strftime("%j")
print("Day of the year:",result)

result = current_datetime.strftime("%d")
print("Day of the month :",result)

result = current_datetime.strftime("%A")
print("Day of the week:",result)

Current datetime : 2024-04-07 10:34:16.078123
Current year : 2024
Month of the year: April
Week number of the year : 14
Day of the year : Sunday
Day of the year: 098
Day of the month : 07
Day of the week: Sunday


In [15]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2004 is a leap year


In [16]:
year = int(input("Enter a year:"))

if (year % 400 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2017 is not a leap year


In [17]:
date_format = "jan 1 2014 2:43PM"
date1 = "%b %d %Y %I:%M%p"
result = datetime.strptime(date_format,date1)
result

datetime.datetime(2014, 1, 1, 14, 43)

In [18]:
from datetime import timedelta
current_datetime = datetime.today()
result = current_datetime + timedelta(days=1)
result

datetime.datetime(2024, 4, 8, 10, 48, 19, 53521)

In [19]:
result = datetime.today() + timedelta(days=-1)
print("Date of yesterday:",result)
result = datetime.today() + timedelta(days=0)
print("Date of today:",result)
result = datetime.today() + timedelta(days=+1)
print("Date of tommorrow:",result)

Date of yesterday: 2024-04-06 10:53:04.980703
Date of today: 2024-04-07 10:53:04.981602
Date of tommorrow: 2024-04-08 10:53:04.982112


In [20]:
current_datetime = datetime.today()
print(current_datetime)

2024-04-07 11:07:31.865861


In [22]:
current_datetime = datetime.now().date()
current_datetime

datetime.date(2024, 4, 7)

In [23]:
for i in range(5):
    result = current_datetime + timedelta(days=i)
    print("Next 5 days starting from today:",result)
    

Next 5 days starting from today: 2024-04-07
Next 5 days starting from today: 2024-04-08
Next 5 days starting from today: 2024-04-09
Next 5 days starting from today: 2024-04-10
Next 5 days starting from today: 2024-04-11


In [25]:
current_datetime = datetime.now()
print(current_datetime)
result = current_datetime.replace(microsecond=0)
print(result)

2024-04-07 11:10:55.505556
2024-04-07 11:10:55


In [28]:
import os 
with open("Abhishek1.txt","w") as f:
    f.write("He is god owns soldier")

with open("Abhishek1.txt","r") as f:
    result = f.read()
    print(result)

He is god owns soldier


In [29]:
os.rename("Abhishek1.txt","Abhishek.txt")

In [30]:
os.listdir()

['.git',
 'Abhi',
 'Abhishek.txt',
 'adaboost.ipynb',
 'Adaboost_Ass.ipynb',
 'ai4i2020.csv',
 'Ann_implementation.ipynb',
 'Assignment_1.ipynb',
 'Assignment_10.ipynb',
 'Assignment_11.ipynb',
 'Assignment_12.ipynb',
 'Assignment_13_LinearR.ipynb',
 'Assignment_2.ipynb',
 'Assignment_3.ipynb',
 'Assignment_4.ipynb',
 'Assignment_6.ipynb',
 'Assignment_7.ipynb',
 'Assignment_8.ipynb',
 'Assignment_9.ipynb',
 'Assignment_DT.ipynb',
 'Assignment_KNN.ipynb',
 'autos_dataset.csv',
 'Bangalore.ipynb',
 'Bengaluru_House_Data.csv',
 'Book2.csv',
 'Boston.csv',
 'CNN.ipynb',
 'CNN_proj_explanation.ipynb',
 'CNN_rev.ipynb',
 'Copy1.txt',
 'Country_clusters.csv',
 'DataFrame.csv',
 'DataFrame.xlsx',
 'dataset_es_train.csv',
 'Decision tree HYP_Tuning.png',
 'Decision Tree.png',
 'DecisionTree.ipynb',
 'Decision_Tree.png',
 'Decision_Tree_HYP.png',
 'Decision_Tree_REG_WithoutHYP.png',
 'Decision_TRee_Working.ipynb',
 'Deep_Learning.ipynb',
 'Deep_Learning_rev.ipynb',
 'DegreeofFreedom.png',
 'dia

In [1]:
import pandas as pd 
df = pd.read_csv("diabetes.csv")
df

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        148             50             35        0  33.6   
1         85             66             29        0  26.6   
2        183             64              0        0  23.3   
3        150             66             23       94  28.1   
4        150             40             35      168  43.1   
..       ...            ...            ...      ...   ...   
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   52        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [1]:
import re 
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall("[a-zA-Z0-9]",string)
if result:
    print("Conatins characters")
else:
    print("Doesnot contains characters")

Conatins characters


In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split("and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [3]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split("is",string)
result

['Python and Machine Learning ',
 ' syllabus of data science and deep learning.']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\ba..\b",str1)
result

['and']

In [8]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s{1}\d{2}\b",sample_string)
result

['123 45', '678 90']

In [9]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [10]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [11]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [12]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [13]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [14]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [16]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [17]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [18]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [21]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [23]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [24]:
str1 = 'new begening of LIFE .'
result = re.findall("LIFE .",str1)
result

['LIFE .']

In [25]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w*",str1)
result

['lazy']

In [26]:
str1 = "we have a lazy cat"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [27]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [29]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [32]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [37]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d..\b",str1)
result

['3.2']

In [38]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\b\d{1,}\b",str1)
result

['1', '12', '13', '345']

In [39]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

    

['fox']
['dog']
[]


In [40]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search("fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [41]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [42]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
result

3


<re.Match object; span=(7, 16), match='exercises'>

In [43]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
result

'The_quick_brown_fox_jumps_over_the_lazy_dog.'

In [44]:
result = re.sub(r"[_]"," ",str1)
result

'The quick brown fox jumps over the lazy dog.'

In [45]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [46]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [47]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [48]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [49]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [50]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [51]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[., ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [52]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [53]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""
result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [54]:
text1 = '"Python", "Data", "Science"'
result = re.findall('""(.+?)""',text1)
result

[]

In [55]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[ ]+"," ",text)
result

'Python., is a general purpose interpreted.'

In [1]:
import numpy as np 
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr1.nbytes

80

In [3]:
arr1 = np.zeros(10)
arr1
arr1[4] = 1 
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [1]:
import numpy as np 
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr1.nbytes

80

In [3]:
arr1 = np.zeros(10)
arr1
arr1[4] = 1 
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [5]:
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
result = reversed(arr1)
list(result)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [11]:
arr1 = np.random.randint(10,20,size=(2,2))
print("Array1:\n",arr1)
arr2 = np.random.randint(20,30,size=(2,2))
print("Array2:\n",arr2)


Array1:
 [[12 17]
 [15 18]]
Array2:
 [[26 20]
 [21 20]]


In [12]:
result = arr1 + arr2
result

array([[38, 37],
       [36, 38]])

In [13]:
result = arr1 - arr2
result

array([[-14,  -3],
       [ -6,  -2]])

In [14]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [15]:
import math 
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [16]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [17]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n", arr1)
result = np.mean(arr1,axis=1)
print("Mean across rows>>",result)
result = np.mean(arr1,axis=0)
print("Mean across columns>>",result)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across rows>> [2. 5. 8.]
Mean across columns>> [4. 5. 6.]


In [18]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [19]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
arr1 = np.random.randint(0,9,size=(3,3))
arr1

array([[7, 3, 0],
       [6, 2, 6],
       [0, 2, 6]])

In [21]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[:: , ::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [22]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [24]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [25]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [26]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [27]:
arr1 = np.array([[2,3],[3,9]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [28]:
arr1 = np.random.randint(1,20,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [ 6  9 19 19 19  6 11 17 16  3 13 16 10 10  2  1  9 15 13  9 19 10  3  7
 19  6  2 10 19  1]


10.633333333333333

In [29]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [30]:
arr1 = np.random.random((3,3,3))
print("Array:\n",arr1)

Array:
 [[[0.59487441 0.10470628 0.19630545]
  [0.48752783 0.90303398 0.51110529]
  [0.70346214 0.68425929 0.25808126]]

 [[0.25234899 0.54977526 0.45515786]
  [0.31602833 0.15504699 0.49991841]
  [0.63350563 0.22009164 0.97653516]]

 [[0.45864587 0.34975451 0.33557396]
  [0.27850098 0.55769171 0.33318808]
  [0.12853448 0.09480222 0.79502277]]]


In [31]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
result = np.max(arr1)
print("Maximum value in array:\n",result)
result = np.min(result)
print("Minimum value in array:\n",result)

Array:
 [[0.60768949 0.21477441 0.43044449 0.48140477 0.21332489 0.31237459
  0.4726357  0.46995187 0.46015775 0.51681281]
 [0.83674729 0.10727582 0.0869472  0.77281595 0.17402325 0.05702164
  0.61224308 0.45064865 0.94006979 0.27320463]
 [0.17032929 0.39024288 0.18183465 0.72091063 0.91597449 0.07856401
  0.90375615 0.02900932 0.41784506 0.18088951]
 [0.53747388 0.03487239 0.5067705  0.21649717 0.73429934 0.87798074
  0.42099634 0.16010502 0.27387479 0.00384116]
 [0.32658915 0.58082562 0.20704161 0.22443299 0.64950537 0.58375517
  0.50645489 0.29138432 0.81334538 0.84676283]
 [0.67733278 0.81061013 0.49556459 0.66908069 0.0334447  0.25717894
  0.22143962 0.86679571 0.5258433  0.85260112]
 [0.98481872 0.81069538 0.60537727 0.39922127 0.44830902 0.43034817
  0.76985995 0.66338537 0.52484419 0.17228231]
 [0.6118914  0.02042501 0.38081139 0.00508157 0.2026035  0.58988996
  0.07762424 0.18135685 0.8305541  0.43877195]
 [0.2396931  0.7325198  0.63690484 0.25318448 0.03551107 0.2396754
  0.9

In [32]:
arr1 = np.ones((10,10))
print("Array:\n",arr1)
arr1[1:-1,1:-1] = 0 
arr1

Array:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4,5])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [34]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4,5])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [35]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr1 = np.eye(4,4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
arr1 = np.random.randint(1,9,size=(5,3))
print("Array:\n",arr1)
arr2 = np.random.randint(1,9,size=(3,2))
print("Array:\n",arr2)
result = np.dot(arr1,arr2)
print("Multiplication of the array:\n",result)

Array:
 [[2 3 2]
 [5 4 1]
 [6 6 5]
 [3 7 6]
 [6 1 7]]
Array:
 [[7 7]
 [6 1]
 [3 3]]
Multiplication of the array:
 [[38 23]
 [62 42]
 [93 63]
 [81 46]
 [69 64]]


In [38]:
arr1 = np.array([1,2,3,4,5,6,7,8,8,9])
print("Array:\n",arr1)
result = np.where((arr1 >= 3) & (arr1 <= 8) , arr1*-1 , arr1)
result

Array:
 [1 2 3 4 5 6 7 8 8 9]


array([ 1,  2, -3, -4, -5, -6, -7, -8, -8,  9])

In [39]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [41]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.ceil(arr1)
print("Rounded up :\n",result)
result = np.floor(arr1)
print("Rounded down :\n",result)

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]
Rounded up :
 [[2. 3.]
 [4. 6.]]
Rounded down :
 [[1. 2.]
 [3. 5.]]


In [42]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1,arr2)
result

array([4, 5, 6])

In [43]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [44]:
arr1 = np.random.randint(1,10,size=10)
print("Array :\n",arr1)
result = np.sort(arr1)
print("Sorted array:",result)

Array :
 [4 4 5 1 5 5 8 1 7 9]
Sorted array: [1 1 4 4 5 5 5 7 8 9]


In [45]:
arr1 = np.zeros((5,5))
print("Array :\n",arr1)
result = arr1 + np.arange(5)
result

Array :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [46]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [48]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
result = np.allclose(arr1,arr2)
result


False

In [3]:
import pandas as pd
import numpy as np
arr1 = np.random.randint(1,10,size=10)
print("Array :",arr1)
result = np.where(arr1 >= np.max(arr1) , 0, arr1)
result

Array : [7 5 6 1 3 1 9 3 5 6]


array([7, 5, 6, 1, 3, 1, 0, 3, 5, 6])

In [4]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Array :",arr1)
for i in np.nditer(arr1):
    print(i , end=" ")

Array : [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1 2 3 4 5 6 7 8 9 

In [5]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Array :",arr1)
for i in np.nditer(arr1):
    print(i , end=" ")

Array : [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1 2 3 4 5 6 7 8 9 

In [6]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [7]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array :\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array :
 [[7 1 4]
 [8 9 4]
 [7 6 9]]


array([[7, 1, 4],
       [8, 9, 4],
       [7, 6, 9]])

In [8]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array :\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array :
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [9]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array :\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array :
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [10]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [11]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.median(arr1)

5.5

In [13]:
arr1 = np.random.randint(1,10,size=10)
print("Array :\n",arr1)
result = np.std(arr1)
result

Array :
 [4 6 9 4 4 6 2 8 9 9]


2.4269322199023193

In [14]:
from scipy.stats import mode 
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [15]:
result = np.around(5.3425,1)
result

5.3

In [16]:
arr1 = np.array([[2,3],[3,4]])
print("Array :\n",arr1)
result = np.linalg.inv(arr1)
result

Array :
 [[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [17]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [18]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)[0]
result

6

In [19]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print("Dimension of the array:",arr1.ndim)
arr1.shape
arr2 = np.reshape(arr1 , (2,5,1))
print(arr2)
print("Dimension of the array:",arr2.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension of the array: 1
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
Dimension of the array: 3


In [20]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print(arr1)
print("Dimension of the array:",arr1.ndim)
result = np.reshape(arr1 ,(6,4))
print(arr2)
print("Dimension of the array :",arr2.ndim)

[[[[13  6 19 16]
   [10 16 15  1]
   [19 11  5  6]]

  [[16  5  4 10]
   [15  2  2 11]
   [13  1 16 14]]]]
Dimension of the array: 4
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
Dimension of the array : 3


In [21]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Matrix :\n",arr1)
print("Shape of the array:",arr1.shape)

Matrix :
 [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]
Shape of the array: (3, 4)


In [1]:
import numpy as np 
import pandas as pd 
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [3]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
df

A    B    C
P  NaN  NaN  NaN
Q  NaN  NaN  NaN
R  NaN  NaN  NaN

In [4]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
if df.isnull:
    print("Dataframe is empty")
else:
    print("Dataframe is not empty")

Dataframe is empty


In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6

In [6]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [8]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [9]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
df = pd.DataFrame(np.random.randint(10,40,size=(5,6)))
df

0   1   2   3   4   5
0  19  36  20  37  17  12
1  36  30  15  20  15  36
2  17  37  26  38  17  38
3  25  27  25  15  26  22
4  26  22  16  27  21  11

In [11]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [13]:
s1 = pd.Series([1,2,3,4,5,6])
s2 = s1.copy()
s2[0] = 50 
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [14]:
s2

0    50
1     2
2     3
3     4
4     5
5     6
dtype: int64

In [15]:
df = pd.DataFrame(np.full((4,5),6))
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [16]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [17]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
pd.DataFrame(arr1 , index=list("ABC"))

0  1  2
A  1  2  3
B  4  5  6
C  7  8  9

In [18]:
arr1 = np.random.randint(0,20,size=(4,4))
df = pd.DataFrame(arr1 , columns=list("ABCD"),index=list("PQRS"))
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=1,inplace=True)
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=0,inplace=True)
df

a   b   c   d
p   3  16  19  12
q   9  18   9  10
r  18   8  10  14
s   7  16  10  13

In [19]:
for i in df.items():
    print(i)

('a', p     3
q     9
r    18
s     7
Name: a, dtype: int32)
('b', p    16
q    18
r     8
s    16
Name: b, dtype: int32)
('c', p    19
q     9
r    10
s    10
Name: c, dtype: int32)
('d', p    12
q    10
r    14
s    13
Name: d, dtype: int32)


In [20]:
for i in df.iterrows():
    print(i)

('p', a     3
b    16
c    19
d    12
Name: p, dtype: int32)
('q', a     9
b    18
c     9
d    10
Name: q, dtype: int32)
('r', a    18
b     8
c    10
d    14
Name: r, dtype: int32)
('s', a     7
b    16
c    10
d    13
Name: s, dtype: int32)


In [22]:
df = pd.DataFrame(np.random.randint(10,20,size=(4,4)))
print(df)
arr1 = df.values
arr1

    0   1   2   3
0  15  15  13  13
1  13  14  19  14
2  12  18  18  14
3  18  12  13  12


array([[15, 15, 13, 13],
       [13, 14, 19, 14],
       [12, 18, 18, 14],
       [18, 12, 13, 12]])

In [23]:
df = pd.DataFrame(np.random.randint(10,20,size=(4,4)))
arr1 = df.values
arr1.tolist()

[[14, 19, 13, 19], [14, 17, 15, 13], [15, 17, 15, 12], [13, 11, 18, 14]]

In [24]:
df

0   1   2   3
0  14  19  13  19
1  14  17  15  13
2  15  17  15  12
3  13  11  18  14

In [25]:
df.reset_index(drop=True)

0   1   2   3
0  14  19  13  19
1  14  17  15  13
2  15  17  15  12
3  13  11  18  14

In [27]:
df = pd.DataFrame(np.random.randint(10,20,size=(4,5)))
print(df)
print(df.shape[0])
print(df.shape[1])

    0   1   2   3   4
0  11  16  18  19  13
1  14  17  14  15  16
2  12  11  10  12  11
3  18  11  11  15  13
4
5


In [28]:
s1 = pd.Series(np.arange(50,60))
s2 = pd.Series(np.arange(25,35))
result = s1+s2
result

0    75
1    77
2    79
3    81
4    83
5    85
6    87
7    89
8    91
9    93
dtype: int32

In [29]:
result = s1-s2
result

0    25
1    25
2    25
3    25
4    25
5    25
6    25
7    25
8    25
9    25
dtype: int32

In [30]:
result = s1 * s2
result

0    1250
1    1326
2    1404
3    1484
4    1566
5    1650
6    1736
7    1824
8    1914
9    2006
dtype: int32

In [31]:
result = s1 / s2
result

0    2.000000
1    1.961538
2    1.925926
3    1.892857
4    1.862069
5    1.833333
6    1.806452
7    1.781250
8    1.757576
9    1.735294
dtype: float64

In [32]:
df = pd.read_excel("Sample1.xlsx")
df

Unnamed: 0 First Name   Last Name  Gender        Country  Age  \
0             1      Dulce       Abril  Female  United States   32   
1             2       Mara   Hashimoto  Female  Great Britain   25   
2             3     Philip        Gent    Male         France   36   
3             4   Kathleen      Hanner  Female  United States   25   
4             5    Nereida     Magwood  Female  United States   58   
..          ...        ...         ...     ...            ...  ...   
995         996       Roma  Lafollette  Female  United States   34   
996         997     Felisa        Cail  Female  United States   28   
997         998   Demetria       Abbey  Female  United States   32   
998         999     Jeromy        Danz    Male  United States   39   
999        1000   Rasheeda      Alkire  Female  United States   29   

           Date    Id  
0    15/10/2017  1562  
1    16/08/2016  1582  
2    21/05/2015  2587  
3    15/10/2017  3549  
4    16/08/2016  2468  
..          ...   ...  
995  15/10/2017  2654  
996  16/08/2016  6525  
997  21/05/2015  3265  
998  15/10/2017  3265  
999  16/08/2016  6125  

[1000 rows x 8 columns]

In [33]:
df.head(3)

Unnamed: 0 First Name  Last Name  Gender        Country  Age        Date  \
0           1      Dulce      Abril  Female  United States   32  15/10/2017   
1           2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016   
2           3     Philip       Gent    Male         France   36  21/05/2015   

     Id  
0  1562  
1  1582  
2  2587

In [34]:
df[["First Name","Last Name"]]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [35]:
df = pd.DataFrame(np.arange(1,8))
df

0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [36]:
df = pd.read_csv("diabetes.csv")
df.head(3)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1

In [37]:
df["Age"].mean()

33.243489583333336

In [38]:
df["Age"].sum()

25531

In [39]:
df["Age"].min()

21

In [40]:
df["Age"].max()

81

In [41]:
df = pd.DataFrame(np.random.randint(1,10,size=(5,4)))
df

0  1  2  3
0  4  8  6  2
1  1  3  9  2
2  9  8  2  1
3  1  6  2  5
4  2  2  2  4

In [42]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [43]:
df.groupby(df["Embarked"]).get_group("S")

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [45]:
arr1 = np.random.randint(1,20,size=(4,2))
df = pd.DataFrame(arr1)
df.apply(np.sqrt)

0         1
0  3.872983  4.242641
1  2.449490  1.414214
2  3.000000  3.872983
3  4.123106  4.242641

In [46]:
df = pd.DataFrame(np.random.randint(1,9,size=(3,4)))
df

0  1  2  3
0  5  3  8  3
1  3  2  2  7
2  7  3  3  7

In [47]:
df.apply(lambda x : x**2)

0  1   2   3
0  25  9  64   9
1   9  4   4  49
2  49  9   9  49

In [48]:
df.apply(lambda x : x**3)

0   1    2    3
0  125  27  512   27
1   27   8    8  343
2  343  27   27  343

In [49]:
arr1 = np.random.randint(1,20,size=(4,2))
df = pd.DataFrame(arr1)
print(df)
df.apply(lambda x : x**2)

    0   1
0  18   3
1  13  14
2   2   3
3   6  19


0    1
0  324    9
1  169  196
2    4    9
3   36  361

In [50]:
df = pd.read_csv("diabetes.csv")
df.head(3)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [52]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [53]:
df.head(2)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [54]:
df.tail(2)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
766                     0.349   47        1  
767                     0.315   23        0

In [55]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
print(df)
df["NAME"].apply(lambda x : x.istitle())

        NAME
0  Rudranshi
1      Sanvi
2      Swati
3      Shiva


0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [56]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
print(df)
df["Designation"] = df["Employee"].map(d2)
df

  Employee
0   Saniya
1     Sara
2    Alexa
3    Jenny


Employee         Designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [57]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1 , columns=list("ABCDE"))
df

A  B  C  D  E
0  4  8  5  9  8
1  2  2  8  5  2
2  1  6  1  5  4
3  8  2  6  6  8
4  8  6  3  9  3

In [58]:
df["F"] = [1,2,3,4,5]
df

A  B  C  D  E  F
0  4  8  5  9  8  1
1  2  2  8  5  2  2
2  1  6  1  5  4  3
3  8  2  6  6  8  4
4  8  6  3  9  3  5

In [59]:
df.insert(1,"H",[1,2,1,2,1])
df

A  H  B  C  D  E  F
0  4  1  8  5  9  8  1
1  2  2  2  8  5  2  2
2  1  1  6  1  5  4  3
3  8  2  2  6  6  8  4
4  8  1  6  3  9  3  5

In [60]:
df

A  H  B  C  D  E  F
0  4  1  8  5  9  8  1
1  2  2  2  8  5  2  2
2  1  1  6  1  5  4  3
3  8  2  2  6  6  8  4
4  8  1  6  3  9  3  5

In [61]:
df.drop("A",axis=1,inplace=True)
df

H  B  C  D  E  F
0  1  8  5  9  8  1
1  2  2  8  5  2  2
2  1  6  1  5  4  3
3  2  2  6  6  8  4
4  1  6  3  9  3  5

In [65]:
df.drop(2,axis=0,inplace=True)
df

KeyError: '[2] not found in axis'

In [66]:
df

H  B  C  D  E  F
0  1  8  5  9  8  1
1  2  2  8  5  2  2
3  2  2  6  6  8  4
4  1  6  3  9  3  5

In [67]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
final = pd.Series(list(result))
final

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [68]:
s1 = pd.Series([1,2,3,4,5])
print("Median :",s1.median())
print("Mean:",s1.mean())
print("25th percentile:",s1.quantile(0.25))
print("75th percentile:",s1.quantile(0.75))
print("Maximum :",s1.max())

Median : 3.0
Mean: 3.0
25th percentile: 2.0
75th percentile: 4.0
Maximum : 5


In [69]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  45  22  28  41
z  37  11  38  30
v  46  39  45  16
s  11  45  48  39

In [70]:
df.sort_index()

C   A   B   D
s  11  45  48  39
v  46  39  45  16
x  45  22  28  41
z  37  11  38  30

In [71]:
df.sort_index(axis=1)

A   B   C   D
x  22  28  45  41
z  11  38  37  30
v  39  45  46  16
s  45  48  11  39

In [72]:
df.sort_values("D")

C   A   B   D
v  46  39  45  16
z  37  11  38  30
s  11  45  48  39
x  45  22  28  41

In [73]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})
df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [74]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [75]:
df.drop("A",axis=1,inplace=True)

In [76]:
df

B  C  D
0  1  1  1
1  1  1  1
2  3  3  3
3  4  4  4
4  5  5  5

In [77]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)

df[["First Name","Last Name"]] = df["Full Name"].str.split(expand=True)
df

Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson

In [78]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)

df[["First Name","Last Name"]] = df["Full Name"].str.split(expand=True)
df

Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson