In [1]:
with open("Abhishek.txt","r") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier


In [2]:
with open("Abhishek.txt","r")as f:
    result = f.readline()
    print(result)

Data Science:



In [3]:
text = """1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing"""
with open("Abhishek.txt","a") as f:
    f.write(text)
    f.close()

In [4]:
with open("Abhishek.txt","r") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [5]:
with open("Abhishek.txt","r") as f:
    result = f.readlines()
    final = result[-2:]
    print(final)

[' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [6]:
with open("Abhishek.txt","r") as f:
    result = f.readlines()
    print(result)
    

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [7]:
with open("Abhishek.txt","r") as f:
    result = f.readlines()
    print("No of lines in the text are:",len(result))

No of lines in the text are: 13


In [8]:
with open("Abhishek.txt","r") as f:
    result = f.read()
    print(result)
    print("Number of words in text file are:",len(result))
    

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language ProcessingHe is god owns soldier1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing
Number of words in text file are: 616


In [9]:
import shutil
with open("Copy.txt","r") as f:
    result = f.readlines()
    print(result)

shutil.copy("Abhishek.txt","Copy.txt")

with open("Copy.txt","r") as f:
    result = f.readlines()
    print(result)

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']
['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language ProcessingHe is God owns soldier1st:- Data Science\n', '

In [10]:
from datetime import datetime 

current_datetime = datetime.now()
print("Current date is:",current_datetime)

# Current year 
current_year = current_datetime.year
print("Current year is:",current_year)

# Month of the year
result = current_datetime.strftime("%B")
print("Month of the year:",result)

# Week number of the year
result = current_datetime.strftime("U")
print("Week number of the year:",result)

# Weekday of week 
result = current_datetime.strftime("%A")
print("Weekday of week:",result)

# Day of Year 
result = current_datetime.strftime("%j")
print("Day of Year:",result)

# Day of Month
result = current_datetime.strftime("%d")
print("Day of Month:",result)

# Day of the week 
result = current_datetime.strftime("%A")
print("Day of the Week:",result)

Current date is: 2024-03-19 05:42:32.645951
Current year is: 2024
Month of the year: March
Week number of the year: U
Weekday of week: Tuesday
Day of Year: 079
Day of Month: 19
Day of the Week: Tuesday


In [11]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year") 
else:
    print(f"{year} is not a leap year")

2024 is a leap year


In [12]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2025 is not a leap year


In [15]:
date_format = "jan 1 2014 2:43PM"
date1 = "%b %d %Y %I:%M%p"
result = datetime.strptime(date_format, date1)
result

datetime.datetime(2014, 1, 1, 14, 43)

In [16]:
from datetime import timedelta
current_datetime = datetime.today()
result = current_datetime + timedelta(days=5)
result

datetime.datetime(2024, 3, 24, 6, 17, 47, 976829)

In [17]:
current_datetime = datetime.today()
new_date = current_datetime + timedelta(days=-1)
print("Yesterday date: ", new_date)
result = current_datetime + timedelta(days=0)
print("Todays date: ", result)
result = current_datetime + timedelta(days=+1)
print("Tommorrow date: ", result)

Yesterday date:  2024-03-18 06:21:06.990388
Todays date:  2024-03-19 06:21:06.990388
Tommorrow date:  2024-03-20 06:21:06.990388


In [18]:
current_datetime = datetime.now().date()
for i in range(5):
    new_date = current_datetime + timedelta(days=i)
    print("Tommorrow date: ", new_date)

Tommorrow date:  2024-03-19
Tommorrow date:  2024-03-20
Tommorrow date:  2024-03-21
Tommorrow date:  2024-03-22
Tommorrow date:  2024-03-23


In [19]:
current_datetime = datetime.now()
print("Todays date: ", current_datetime)
result = current_datetime.replace(microsecond=0)
result

Todays date:  2024-03-19 06:29:52.554434


datetime.datetime(2024, 3, 19, 6, 29, 52)

In [20]:
import os 
os.rename("Copy.txt","Copy1.txt")

In [21]:
os.getcwd()

'd:\\abhi python\\Python hands on\\Python-Hands-ON'

In [22]:
os.listdir()

['.git',
 'Abhi',
 'Abhishek.txt',
 'adaboost.ipynb',
 'Adaboost_Ass.ipynb',
 'ai4i2020.csv',
 'Ann_implementation.ipynb',
 'Assignment_1.ipynb',
 'Assignment_10.ipynb',
 'Assignment_11.ipynb',
 'Assignment_12.ipynb',
 'Assignment_13_LinearR.ipynb',
 'Assignment_2.ipynb',
 'Assignment_3.ipynb',
 'Assignment_4.ipynb',
 'Assignment_6.ipynb',
 'Assignment_7.ipynb',
 'Assignment_8.ipynb',
 'Assignment_9.ipynb',
 'Assignment_DT.ipynb',
 'Assignment_KNN.ipynb',
 'autos_dataset.csv',
 'Bangalore.ipynb',
 'Bengaluru_House_Data.csv',
 'Book2.csv',
 'Boston.csv',
 'CNN.ipynb',
 'CNN_proj_explanation.ipynb',
 'CNN_rev.ipynb',
 'Copy1.txt',
 'Country_clusters.csv',
 'DataFrame.csv',
 'DataFrame.xlsx',
 'dataset_es_train.csv',
 'Decision tree HYP_Tuning.png',
 'Decision Tree.png',
 'DecisionTree.ipynb',
 'Decision_Tree.png',
 'Decision_Tree_HYP.png',
 'Decision_Tree_REG_WithoutHYP.png',
 'Decision_TRee_Working.ipynb',
 'Deep_Learning.ipynb',
 'Deep_Learning_rev.ipynb',
 'DegreeofFreedom.png',
 'dia

In [2]:
import re 
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall(r"\w{1,}",string)
result

['Python',
 'and',
 'Machine',
 'Learning',
 '7741',
 'is',
 'syllabus',
 'of',
 'Data',
 'Science']

In [3]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [4]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"is",string)
result

['Python and Machine Learning ',
 ' syllabus of data science and deep learning.']

In [11]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\b[a-z]{1,}\b",str1)
result

['and']

In [12]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\b[a-z]{1,}\b",str1)
result

['and']

In [13]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [20]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [21]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [22]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [25]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py*",str1)
result

['py', 'py']

In [26]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [27]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [29]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [30]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [31]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b[k-n]{3,}\b",str1)
result

[]

In [32]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [33]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [34]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [35]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [36]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [37]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [38]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [39]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [40]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [41]:
str1 = 'new begening of LIFE .'
result = re.findall("LIFE .",str1)
result

['LIFE .']

In [42]:
str1 = "today is the very lazy day"
result = re.findall(r"\b[a-z]+[z]+[a-z]",str1)
result

['lazy']

In [43]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]+[z]+[a-y]",str1)
result

['lazy']

In [44]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [45]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [49]:
str1 = "9821 maya"
result = re.findall(r"^9...",str1)
result

['9821']

In [50]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [52]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [53]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [55]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d..\b",str1)
result

['3.2']

In [56]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\b\d{1,}\b",str1)
result

['1', '12', '13', '345']

In [58]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for i in Searched_words:
    result = re.findall(i , Sample_text)
    print(result)

['fox']
['dog']
[]


In [59]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for i in Searched_words:
    result = re.findall(i , Sample_text)
    print(result)

['fox']
['dog']
[]


In [60]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search("fox",Sample_text)
print(f"Start index is {result.start()} and end index is {result.end()}")


Start index is 16 and end index is 19


In [61]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [62]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [63]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(f"The ocuurence of the substring is:",len(result))
result = re.search(r"exercises",Sample_text)
print(f"The position of the substring is start from {result.start()} and end {result.end()}")

The ocuurence of the substring is: 3
The position of the substring is start from 7 and end 16


In [65]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
result

'The_quick_brown_fox_jumps_over_the_lazy_dog.'

In [66]:
result = re.sub(r"_"," ",result)
result

'The quick brown fox jumps over the lazy dog.'

In [67]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [68]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [69]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [70]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [71]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w{1,}",str1)
result

['python', 'pythonnn']

In [72]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [73]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [74]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [76]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [77]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [79]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [80]:
text1 = '"Python", "Data", "Science"'
result = re.findall("""(.+?)""",text1)
result

['"',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 '"',
 ',',
 ' ',
 '"',
 'D',
 'a',
 't',
 'a',
 '"',
 ',',
 ' ',
 '"',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 '"']

In [1]:
import numpy as np 
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
arr1
arr1[4] = 1 
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [7]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = list(reversed(arr1))
arr2

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [10]:
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [11]:
arr2 = list(reversed(arr1))
arr2

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [12]:
arr1 = np.random.randint(10,20,size=(2,2))
print("Arr1 :\n",arr1)
arr2 = np.random.randint(30,40,size=(2,2))
print("Arr2 :\n",arr2)


Arr1 :
 [[10 11]
 [18 17]]
Arr2 :
 [[34 34]
 [30 37]]


In [13]:
add1 = arr1 + arr2
add1

array([[44, 45],
       [48, 54]])

In [14]:
sub1 = arr1 - arr2
sub1

array([[-24, -23],
       [-12, -20]])

In [15]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [16]:
import math
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [17]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Arr1 :\n",arr1)
result = np.mean(arr1,axis=1)
print("Mean across row>>",result)
result = np.mean(arr1,axis=0)
print("Mean across col>>",result)


Arr1 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across row>> [2. 5. 8.]
Mean across col>> [4. 5. 6.]


In [19]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [20]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [21]:
arr1 = np.random.randint(0,8,size=(3,3))
arr1

array([[6, 2, 2],
       [4, 0, 6],
       [3, 1, 3]])

In [22]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Arr1:\n",arr1)
arr1[:: , ::-1]

Arr1:
 [[4 9]
 [6 4]]


array([[9, 4],
       [4, 6]])

In [23]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Arr1:\n",arr1)
arr1[:: , ::-1]

Arr1:
 [[6 5]
 [1 6]]


array([[5, 6],
       [6, 1]])

In [24]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Arr1:\n",arr1)
arr1[::-1]

Arr1:
 [[3 1]
 [8 4]]


array([[8, 4],
       [3, 1]])

In [25]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Arr1:\n",arr1)
arr1[::-1]

Arr1:
 [[6 8]
 [2 5]]


array([[2, 5],
       [6, 8]])

In [26]:
arr1 = np.array([1,2,0,0,4,0])
print("Arr1:\n",arr1)
result = np.nonzero(arr1)
result

Arr1:
 [1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

In [27]:
arr1 = np.array([1,2,0,0,4,0])
print("Arr1:\n",arr1)
result = np.nonzero(arr1)
result

Arr1:
 [1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

In [28]:
arr1 = np.array([[1,2],[3,4]])
print("Matrix :\n",arr1)
result = np.linalg.det(arr1)
print("Determinant of array:",result)

Matrix :
 [[1 2]
 [3 4]]
Determinant of array: -2.0000000000000004


In [29]:
arr1 = np.array([[1,2],[3,4]])
print("Matrix :\n",arr1)
result = np.linalg.det(arr1)
result

Matrix :
 [[1 2]
 [3 4]]


-2.0000000000000004

In [30]:
arr1 = np.array([[1,2],[3,4]])
print("Matrix :\n",arr1)
result = np.linalg.inv(arr1)
result

Matrix :
 [[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [31]:
arr1 = np.random.randint(1,10,size=(30))
print("Matrix :\n",arr1)
result = np.mean(arr1)
print("Mean of the matrix :\n",result)

Matrix :
 [8 1 2 2 5 5 6 2 4 4 8 5 8 1 1 5 4 9 1 3 7 9 6 1 9 2 8 6 2 4]
Mean of the matrix :
 4.6


In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
arr2 = np.where(arr1 > 5)
print("Array:",arr2)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Array: (array([5, 6, 7, 8, 9], dtype=int64),)


In [33]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
arr2 = np.where(arr1 < 5)
print("Array:",arr2)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Array: (array([0, 1, 2, 3], dtype=int64),)


In [34]:
arr1 = np.random.random((3,3,3))
print("Array:",arr1)

Array: [[[4.88730569e-01 3.56920829e-01 2.42508392e-01]
  [4.48107414e-01 8.75485443e-01 3.56541022e-01]
  [3.66713683e-01 8.64307399e-01 5.25285292e-01]]

 [[1.98871362e-01 4.25587139e-02 2.72575545e-01]
  [1.31645416e-01 3.22192513e-01 5.48046993e-01]
  [8.04453197e-01 8.37471190e-01 9.17871152e-01]]

 [[6.26342125e-04 7.11731560e-01 1.86533896e-01]
  [7.95319527e-04 4.38964339e-01 1.23020702e-01]
  [6.88349708e-01 8.68910752e-01 2.28603141e-01]]]


In [35]:
arr1 = np.random.rand(10,10)
print("Array:",arr1)
print("Maximum value:",np.max(arr1))
print("Minimum value:",np.min(arr1))

Array: [[0.25965574 0.51770866 0.63893896 0.31347077 0.99650565 0.0413454
  0.39819474 0.88668732 0.46072776 0.17925184]
 [0.73728531 0.351814   0.32322639 0.73513073 0.41387135 0.2859403
  0.02291473 0.07483628 0.06943104 0.02348703]
 [0.86353857 0.42612635 0.78538235 0.14394091 0.28311185 0.41581987
  0.53537867 0.3714331  0.4910455  0.12789041]
 [0.4929332  0.260212   0.1530795  0.1200643  0.10434506 0.39551414
  0.68099764 0.48991928 0.49070387 0.44787651]
 [0.14597504 0.49228198 0.2915735  0.74903079 0.17378252 0.53644506
  0.0367095  0.1231189  0.84864917 0.35036779]
 [0.83885625 0.23851014 0.51414978 0.88038408 0.32392845 0.11952261
  0.50097429 0.94804642 0.55159519 0.05196317]
 [0.72878295 0.88408639 0.77008209 0.39398151 0.18763577 0.01197499
  0.46362106 0.48443059 0.32134804 0.87093931]
 [0.17964001 0.0385772  0.13704649 0.34902469 0.76342317 0.88773951
  0.21709451 0.46625983 0.92969878 0.70342206]
 [0.71991313 0.75806838 0.63018562 0.54003414 0.30474644 0.25206373
  0.306

In [36]:
arr1 = np.ones((10,10))
arr1[1:-1, 1:-1] = 0 
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0 
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0 
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [40]:
arr1 = np.zeros((5,5),dtype=int)
print(arr1)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [41]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arr1 = np.eye(4,4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1, arr2)
result

array([[ 43,  99],
       [ 41, 100],
       [ 39,  90],
       [ 26,  59],
       [ 29,  72]])

In [44]:
result = np.dot(arr1,arr2)
result

array([[ 43,  99],
       [ 41, 100],
       [ 39,  90],
       [ 26,  59],
       [ 29,  72]])

In [46]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
arr1[(arr1 >= 3) & (arr1 <= 8)] *= -1
arr1

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [47]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
print(arr1)
arr1[(arr1 >= 3) & (arr1 <= 8)] *= -1
arr1

[ 1  2  3  4  5  6  7  8 44  9 33  6  5 10]


array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [48]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8) , -1*arr1 , arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [49]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8) , -1*arr1 , arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [50]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Matrix :\n", arr1)
result = np.around(arr1)
result

Matrix :
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1., 3.],
       [3., 5.]])

In [51]:
result = np.ceil(arr1)
result

array([[2., 3.],
       [4., 6.]])

In [52]:
result = np.floor(arr1)
result

array([[1., 2.],
       [3., 5.]])

In [53]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [54]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [55]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [56]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [57]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
result = np.sort(arr1)
result

Array: [1 1 3 1 4 5 4 7 9 3]


array([1, 1, 1, 3, 3, 4, 4, 5, 7, 9])

In [58]:
arr1 = np.zeros((5,5))
print("Original array:\n",arr1)
result = arr1 + np.arange(5)
result

Original array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [59]:
arr1 = np.zeros((5,5))
print("Original array:\n",arr1)
result = arr1 + np.arange(5)
result

Original array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [60]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [61]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [62]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
result = np.allclose(arr1,arr2)
result

False

In [63]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
result = np.allclose(arr1,arr2)
result

False

In [64]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
result = np.where((arr1 >= np.max(arr1)) , 0 , arr1)
result

Array: [4 7 1 6 2 9 4 3 8 6]


array([4, 7, 1, 6, 2, 0, 4, 3, 8, 6])

In [66]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
result = np.where((arr1 >= np.max(arr1)),0,arr1)
result

Array: [7 9 7 6 7 9 3 8 8 5]


array([7, 0, 7, 6, 7, 0, 3, 8, 8, 5])

In [67]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Array:\n",arr1)
for i in np.nditer(arr1):
    print(i , end=" ")

Array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1 2 3 4 5 6 7 8 9 

In [68]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Array:\n",arr1)
for i in np.nditer(arr1):
    print(i , end=" ")

Array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1 2 3 4 5 6 7 8 9 

In [69]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [70]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [71]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array:\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array:
 [[1 2 1]
 [2 3 8]
 [1 5 7]]


array([[1, 2, 1],
       [1, 5, 7],
       [2, 3, 8]])

In [72]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array:\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array:
 [[6 2 6]
 [6 2 2]
 [6 5 5]]


array([[6, 2, 2],
       [6, 5, 5],
       [6, 2, 6]])

In [73]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [74]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [75]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = mode(arr1)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


ModeResult(mode=1, count=1)

In [76]:
result = np.around(5.4322 , 3)
result

5.432

In [77]:
result = np.around(5.4322 , 2)
result

5.43

In [78]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [79]:
arr1 = np.array([[2,3],[3,4]])
result = np.cov(arr1)
result

array([[0.5, 0.5],
       [0.5, 0.5]])

In [80]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [81]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)[0]
result

6

In [83]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Matrix:\n", arr1)
print("Dimension of the matrix:",arr1.ndim)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
print(arr2)
print("Dimension of the array is :",arr2.ndim)

Matrix:
 [ 1  2  3  4  5  6  7  8  9 10]
Dimension of the matrix: 1
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
Dimension of the array is : 3


In [84]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print(arr1)
arr2 = np.reshape(arr1 , (6,4))
print(arr2)

[[[[4 6 2 6]
   [8 5 7 8]
   [5 8 6 7]]

  [[8 5 7 1]
   [4 3 9 7]
   [3 5 6 3]]]]
[[4 6 2 6]
 [8 5 7 8]
 [5 8 6 7]
 [8 5 7 1]
 [4 3 9 7]
 [3 5 6 3]]


In [85]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
arr1.shape

(3, 4)